# Generated by Django 5.0.3 on 2024-03-27 21:47

from django.db import migrations


def forward_company_event_image(apps, schema_editor):
    company_events = apps.get_model("events", "CompanyEvent")
    # this does give one company preference if there are multiple companies, but those events should have their own image
    for ce in company_events.objects.select_related(
        "event__image", "company__image"
    ).iterator(chunk_size=100):
        if not ce.event.image and ce.company.image:
            ce.event.image = ce.company.image
            ce.event.save()


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_eventuseraction"),
    ]

    operations = [migrations.RunPython(forward_company_event_image)]
