# Generated by Django 5.1.2 on 2025-03-19 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_auto_20240327_2247"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeregistrationFeedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "cause",
                    models.TextField(
                        choices=[
                            ("sick", "Sykdom"),
                            ("economic", "Økonomi"),
                            ("time", "Tidsklemma"),
                            ("school", "Skole"),
                            ("no_familiar_faces", "Ingen kjente påmeldte"),
                            ("admin", "Meldt av administrator"),
                            ("missing_payment", "Mangler betaling"),
                            ("other", "Annet"),
                        ],
                        default="other",
                        verbose_name="årsak",
                    ),
                ),
                ("text", models.TextField(default="", verbose_name="begrunnelse")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deregistrations",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "avregistrering",
                "ordering": ["-pk"],
            },
        ),
    ]
