# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-31 17:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20160309_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(45)], verbose_name='beskrivelse'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ingress',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(25)], verbose_name='ingress'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ingress_short',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(25)], verbose_name='kort ingress'),
        ),
        migrations.AlterField(
            model_name='fieldofstudyrule',
            name='field_of_study',
            field=models.SmallIntegerField(choices=[(0, 'Gjest'), (1, 'Bachelor i Informatikk'), (10, 'Programvaresystemer'), (11, 'Databaser og søk'), (12, 'Algoritmer og datamaskiner'), (13, 'Spillteknologi'), (14, 'Kunstig intelligens'), (15, 'Helseinformatikk'), (16, 'Interaksjonsdesign, spill- og læringsteknologi'), (30, 'Annen mastergrad'), (80, 'PhD'), (90, 'International'), (100, 'Annet Onlinemedlem')], verbose_name='studieretning'),
        ),
    ]
