# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-06 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("events", "0010_auto_20160906_1703")]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="image", new_name="old_image"
        )
    ]
