# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-07 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20161006_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyevent',
            options={'ordering': ('company',), 'permissions': (('view_companyevent', 'View CompanyEvent'),), 'verbose_name': 'bedrift', 'verbose_name_plural': 'bedrifter'},
        ),
    ]
