# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 21:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='show_as_attending_event',
            field=models.BooleanField(default=False, verbose_name='vis som påmeldt arrangementet'),
        ),
    ]
