# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 20:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_organizer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('view_event', 'View Event'),), 'verbose_name': 'arrangement', 'verbose_name_plural': 'arrangementer'},
        ),
        migrations.AddField(
            model_name='attendee',
            name='show_as_attending_event',
            field=models.NullBooleanField(default=None, verbose_name='vis som skal på sosiale arrangement'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ingress',
            field=models.TextField(help_text='En ingress som blir vist før beskrivelsen.', validators=[django.core.validators.MinLengthValidator(25)], verbose_name='ingress'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ingress_short',
            field=models.CharField(help_text='En kort ingress som blir vist på forsiden', max_length=150, validators=[django.core.validators.MinLengthValidator(25)], verbose_name='kort ingress'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='arrangør'),
        ),
    ]
