# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0016_event_organizer")]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="show_as_attending_event",
            field=models.BooleanField(
                default=False, verbose_name="vis som påmeldt arrangementet"
            ),
        )
    ]
