# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-05 22:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20180221_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='show_as_attending_event',
        ),
    ]
