# Generated by Django 2.1 on 2019-04-03 19:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20180221_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceevent',
            options={'permissions': (('show_attendanceevent', 'Show AttendanceEvent'),), 'verbose_name': 'påmelding', 'verbose_name_plural': 'påmeldinger'},
        ),
        migrations.AlterModelOptions(
            name='attendee',
            options={'ordering': ['timestamp'], 'permissions': (('show_attendee', 'Show Attendee'),)},
        ),
        migrations.AlterModelOptions(
            name='companyevent',
            options={'ordering': ('company',), 'permissions': (('show_companyevent', 'Show CompanyEvent'),), 'verbose_name': 'bedrift', 'verbose_name_plural': 'bedrifter'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('show_event', 'Show Event'),), 'verbose_name': 'arrangement', 'verbose_name_plural': 'arrangementer'},
        ),
        migrations.AlterModelOptions(
            name='fieldofstudyrule',
            options={'permissions': (('show_fieldofstudyrule', 'Show FieldOfStudyRule'),)},
        ),
        migrations.AlterModelOptions(
            name='graderule',
            options={'permissions': (('show_graderule', 'Show GradeRule'),)},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'permissions': (('show_reservation', 'Show Reservation'),), 'verbose_name': 'reservasjon', 'verbose_name_plural': 'reservasjoner'},
        ),
        migrations.AlterModelOptions(
            name='reservee',
            options={'ordering': ['id'], 'permissions': (('show_reservee', 'Show Reservee'),), 'verbose_name': 'reservasjon', 'verbose_name_plural': 'reservasjoner'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'permissions': (('show_rule', 'Show Rule'),)},
        ),
        migrations.AlterModelOptions(
            name='rulebundle',
            options={'permissions': (('show_rulebundle', 'Show RuleBundle'),)},
        ),
        migrations.AlterModelOptions(
            name='usergrouprule',
            options={'permissions': (('show_usergrouprule', 'Show UserGroupRule'),)},
        ),
        migrations.AlterField(
            model_name='event',
            name='ingress',
            field=models.TextField(help_text='En ingress som blir vist før beskrivelsen.', validators=[django.core.validators.MinLengthValidator(25)], verbose_name='ingress'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ingress_short',
            field=models.CharField(help_text='En kort ingress som blir vist på forsiden', max_length=150, validators=[django.core.validators.MinLengthValidator(25)], verbose_name='kort ingress'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='arrangør'),
        ),
        migrations.AlterField(
            model_name='fieldofstudyrule',
            name='field_of_study',
            field=models.SmallIntegerField(choices=[(0, 'Gjest'), (1, 'Bachelor i Informatikk'), (10, 'Programvaresystemer'), (11, 'Databaser og søk'), (12, 'Algoritmer og datamaskiner'), (13, 'Spillteknologi'), (14, 'Kunstig intelligens'), (15, 'Helseinformatikk'), (16, 'Interaksjonsdesign, spill- og læringsteknologi'), (30, 'Annen mastergrad'), (40, 'Sosialt medlem'), (80, 'PhD'), (90, 'International'), (100, 'Annet Onlinemedlem')], verbose_name='studieretning'),
        ),
    ]
