# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-19 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20180207_1742'),
        ('events', '0017_auto_20180221_2200'),
    ]

    operations = [
    ]
