# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 15:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_merge_20180319_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ingress',
            field=models.TextField(help_text='En ingress som blir vist før beskrivelsen.', validators=[django.core.validators.MinLengthValidator(25)], verbose_name='ingress'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ingress_short',
            field=models.CharField(help_text='En kort ingress som blir vist på forsiden', max_length=150, validators=[django.core.validators.MinLengthValidator(25)], verbose_name='kort ingress'),
        ),
    ]
