# Generated by Django 2.0.13 on 2019-05-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20190506_1719'),
        ('events', '0019_event_visible'),
    ]

    operations = [
    ]
