# Generated by Django 2.1.9 on 2019-06-29 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20190506_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_capacity', models.PositiveIntegerField(verbose_name='maks-kapasitet')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.AttendanceEvent', verbose_name='Påmelding')),
                ('description', models.CharField(blank=False, max_length=80, null=False, verbose_name='Kort beskrivelse')),
                ('rule_bundles', models.ManyToManyField(blank=True, to='events.RuleBundle')),
            ],
            options={
                'verbose_name': 'Arrengementsregistrering',
                'verbose_name_plural': 'Arrangementsregistreringer',
                'ordering': ('attendance', 'description', 'max_capacity'),
                'permissions': (('view_registration', 'View Registration'),),
                'default_permissions': ('add', 'change', 'delete'),
            },
        ),
        migrations.AddField(
            model_name='attendee',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.Registration', verbose_name='Påmeldte'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='registration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_seats', to='events.Registration', verbose_name='Reservasjon'),
        ),
    ]
