# Generated by Django 2.1.9 on 2019-06-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20190629_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceevent',
            name='max_capacity',
        ),
    ]
