# Generated by Django 2.2.10 on 2020-03-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0024_auto_20191010_2259"),
        ("events", "0024_attendee_allow_pictures"),
    ]

    operations = []
