# Generated by Django 2.1.9 on 2019-06-30 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_remove_attendanceevent_max_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceevent',
            name='rule_bundles',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='attendance_event',
        ),
        migrations.AlterField(
            model_name='attendee',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.Registration', verbose_name='Registrering'),
        ),
    ]
