# Generated by Django 2.2.10 on 2020-03-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0025_merge_20200301_1555"),
        ("events", "0025_auto_20200229_1046"),
    ]

    operations = []
