# Generated by Django 3.0.5 on 2020-04-20 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companyprofile", "0006_auto_20190506_1719"),
        ("events", "0026_merge_20200316_1149"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="companies",
            field=models.ManyToManyField(
                related_name="events",
                through="events.CompanyEvent",
                to="companyprofile.Company",
                verbose_name="Bedrifter",
            ),
        ),
        migrations.AlterField(
            model_name="companyevent",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_events",
                to="events.Event",
                verbose_name="arrangement",
            ),
        ),
    ]
