# Generated by Django 3.0.6 on 2020-05-25 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0027_auto_20200420_1143"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendanceevent",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("pk",),
                "permissions": (("view_attendanceevent", "View AttendanceEvent"),),
                "verbose_name": "påmelding",
                "verbose_name_plural": "påmeldinger",
            },
        ),
        migrations.AlterModelOptions(
            name="rule",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("id",),
                "permissions": (("view_rule", "View Rule"),),
            },
        ),
        migrations.AlterModelOptions(
            name="rulebundle",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("id",),
                "permissions": (("view_rulebundle", "View RuleBundle"),),
            },
        ),
    ]
