# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20150926_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacy',
            name='visible_as_attending_events',
            field=models.BooleanField(default=False, verbose_name='synlig som påmeldt alle sosiale arrangement'),
        ),
    ]
