# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0003_privacy_visible_as_attending_events")]

    operations = [
        migrations.AlterField(
            model_name="privacy",
            name="visible_as_attending_events",
            field=models.BooleanField(
                default=False, verbose_name="vis på sosiale arrangement"
            ),
        )
    ]
