# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-05 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_privacy_visible_as_attending_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacy',
            name='visible_as_attending_events',
        ),
    ]
