# Generated by Django 2.1 on 2019-04-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180221_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacy',
            options={'permissions': (('show_privacy', 'Show Privacy'),), 'verbose_name': 'personvern', 'verbose_name_plural': 'personvern'},
        ),
    ]
