# Generated by Django 2.1.11 on 2020-02-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0005_auto_20190506_1719")]

    operations = [
        migrations.AddField(
            model_name="privacy",
            name="allow_pictures",
            field=models.BooleanField(
                default=False, verbose_name="greit å ta bilder på arrangement"
            ),
        )
    ]
