# Generated by Django 2.2.10 on 2020-03-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_auto_20191122_2012"),
        ("profiles", "0006_privacy_allow_pictures"),
    ]

    operations = []
