# Generated by Django 3.0.10 on 2020-10-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_merge_20200301_1555"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privacy",
            name="allow_pictures",
            field=models.BooleanField(
                default=None, null=True, verbose_name="greit å ta bilder på arrangement"
            ),
        ),
        migrations.AlterField(
            model_name="privacy",
            name="visible_as_attending_events",
            field=models.BooleanField(
                default=None, null=True, verbose_name="vis på påmeldingsarrangement"
            ),
        ),
    ]
