# Generated by Django 3.0.10 on 2020-11-06 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0008_auto_20201024_1903"),
    ]

    operations = [
        migrations.RemoveField(model_name="privacy", name="id",),
        migrations.AlterField(
            model_name="privacy",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="privacy",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
