# Generated by Django 3.0.10 on 2020-11-06 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_privacy_for_all(apps, schema_editor):
    # we used to have that an user could not have a privacy,
    # this creates it for everyone
    User = apps.get_model("authentication", "OnlineUser")
    Privacy = apps.get_model("profiles", "Privacy")
    for user in User.objects.filter(privacy=None):
        Privacy.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0008_auto_20201024_1903"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privacy",
            name="id",
        ),
        migrations.AlterField(
            model_name="privacy",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="privacy",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(create_privacy_for_all),
    ]
