# Generated by Django 3.0.10 on 2020-11-06 17:16

from django.conf import settings
from django.db import migrations, models
from apps.authentication.models import OnlineUser as User
import django.db.models.deletion

from apps.profiles.models import Privacy


def create_privacy_for_all():
    # we used to have that an user could not have a privacy,
    # this creates it for everyone
    for user in User.objects.filter(privacy=None):
        Privacy.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0008_auto_20201024_1903"),
    ]

    operations = [
        migrations.RemoveField(model_name="privacy", name="id",),
        migrations.AlterField(
            model_name="privacy",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="privacy",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(),
    ]
