# Generated by Django 3.2.24 on 2024-03-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0009_auto_20201106_1816"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privacy",
            name="expose_address",
            field=models.BooleanField(default=False, verbose_name="vis addresse"),
        ),
        migrations.AlterField(
            model_name="privacy",
            name="expose_email",
            field=models.BooleanField(default=False, verbose_name="vis epost"),
        ),
        migrations.AlterField(
            model_name="privacy",
            name="expose_nickname",
            field=models.BooleanField(default=False, verbose_name="vis kallenavn"),
        ),
        migrations.AlterField(
            model_name="privacy",
            name="expose_phone_number",
            field=models.BooleanField(default=False, verbose_name="vis telefonnummer"),
        ),
        migrations.AlterField(
            model_name="privacy",
            name="visible_for_other_users",
            field=models.BooleanField(
                default=False, verbose_name="profil synlig for andre brukere"
            ),
        ),
    ]
