# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-06 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='issues',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='public_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
