# Generated by Django 2.0.13 on 2019-05-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0002_auto_20181106_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'default_permissions': ('add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='repositorylanguage',
            options={'default_permissions': ('add', 'change', 'delete')},
        ),
    ]
