version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: uv 
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"
    groups:
      patches:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"

