pipeline:
    tests:
        when:
            event: pull_request
        image: registry.online.ntnu.no/dotkom/onlineweb4-testbase
        commands:
            - cp onlineweb4/settings/example-local.py onlineweb4/settings/local.py
            - tox -e isort
            - tox -e flake8
            - tox -e tests
        auth_config:
            username: $$REGISTRY_USERNAME
            password: $$REGISTRY_PASSWORD
            email: dotkom@online.ntnu.no
        volumes:
            - /tmp/drone/ow4test-cache/.tox:/drone/src/github.com/dotKom/onlineweb4/.tox
    deploy:
        ssh:
            when:
                branch: develop
                event: push
            host: nansen.dotkom
            port: 22
            user: root
            commands:
                - /srv/www/ow4dev/deploy.sh

