setup_tasks:
  - npm install -g less
  - apt-get update
  - apt-get install -y libldap2-dev libsasl2-dev libssl-dev

tasks:
  - tox -e flake8
  - tox -e isort
  - tox -e tests
  - tox -e coverage

verbose_tasks:
  - tox -e coverage

coverage:
  path: coverage.xml
  parser: python
