default_language_version:
    python: python3.12
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: "v0.11.2"
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
