FROM python:3.7
MAINTAINER dotkom

ENV APP_DIR=/srv/app

RUN mkdir -p $APP_DIR

COPY poetry.lock pyproject.toml /$APP_DIR/

WORKDIR $APP_DIR

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    libjpeg-dev \
    ghostscript

RUN pip install poetry

RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi -E "prod"

ENV DJANGO_SETTINGS_MODULE onlineweb4.settings

CMD ["bash"]
