# Generated by Django 2.0.13 on 2019-05-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0002_auto_20171127_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('view_client', 'View Client'),)},
        ),
    ]
