# Generated by Django 2.1 on 2019-04-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0002_auto_20171127_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': (('show_client', 'Show Client'),)},
        ),
    ]
