# Generated by Django 2.1.8 on 2019-05-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0003_auto_20190506_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='redirect_uris',
            field=models.TextField(blank=True, help_text='Allowed URIs list, space separated'),
        ),
    ]
