# Generated by Django 2.1.15 on 2020-03-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0004_auto_20190521_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
