# Generated by Django 3.0.10 on 2021-04-02 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sso", "0005_auto_20210321_1621"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationConsent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_given",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date Given"),
                ),
                (
                    "approved_scopes",
                    models.TextField(blank=True, verbose_name="Tilganger"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bruker",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "client")},
            },
        ),
    ]
