# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("companyprofile", "0003_company_image")]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="short_description",
            field=models.TextField(verbose_name="kort beskrivelse"),
        )
    ]
