# Generated by Django 2.1 on 2019-04-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0005_auto_20170130_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'permissions': (('show_company', 'Show Company'),), 'verbose_name': 'Bedrift', 'verbose_name_plural': 'Bedrifter'},
        ),
    ]
