# Generated by Django 3.0.5 on 2020-04-26 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("companyprofile", "0006_auto_20190506_1719")]

    operations = [
        migrations.AddField(
            model_name="company",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Opprettet dato",
            ),
            preserve_default=False,
        )
    ]
