EVENT_REGISTRATION = 'event_registration'
EVENT_UPDATES = 'event_updates'
EVENT_WAIT_LIST_BUMP = 'event_wait_list_bump'
EVENT_FEEDBACK_CREATED = 'feedback_created'

ARTICLE_CREATED = 'article_created'
OFFLINE_CREATED = 'offline_created'

ANNOUNCEMENT = 'announcement'
COMMITTEE_ANNOUNCEMENT = 'committee_announcement'

WINE_PUNISHMENT = 'wine_punishment'

NOTIFICATION_TYPES = [
    EVENT_REGISTRATION,
    EVENT_UPDATES,
    EVENT_WAIT_LIST_BUMP,
    EVENT_FEEDBACK_CREATED,
    ARTICLE_CREATED,
    OFFLINE_CREATED,
    ANNOUNCEMENT,
    COMMITTEE_ANNOUNCEMENT,
    WINE_PUNISHMENT,
]
