# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 20:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("webshop", "0004_auto_20151118_2242")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Antall på lager. Blankt vil si uendelig.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_sizes",
                to="webshop.Product",
            ),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="stock",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Antall på lager. Blankt vil si uendelig.",
                null=True,
            ),
        ),
    ]
