# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 15:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0005_auto_20160428_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images_csv',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
