# Generated by Django 2.1 on 2019-04-03 19:32

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0006_auto_20181110_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': (('show_category', 'Show Category'),), 'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategorier'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('show_order', 'Show Order'),), 'verbose_name': 'Bestilling', 'verbose_name_plural': 'Bestillinger'},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'permissions': (('show_order_line', 'Show Order Line'),)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('show_product', 'Show Product'),), 'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkter'},
        ),
        migrations.AlterField(
            model_name='product',
            name='images_csv',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
