# Generated by Django 3.0.6 on 2020-05-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webshop", "0007_auto_20190506_1719"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("order_line", "product", "id"),
                "permissions": (("view_order", "View Order"),),
                "verbose_name": "Bestilling",
                "verbose_name_plural": "Bestillinger",
            },
        ),
        migrations.AlterModelOptions(
            name="orderline",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("pk",),
                "permissions": (("view_order_line", "View Order Line"),),
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("category", "stock", "slug"),
                "permissions": (("view_product", "View Product"),),
                "verbose_name": "Produkt",
                "verbose_name_plural": "Produkter",
            },
        ),
    ]
