# Generated by Django 2.1.9 on 2019-08-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0008_auto_20190823_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_type',
            field=models.CharField(choices=[('NONE', 'NONE'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('RAW_FISH', 'RAW_FISH'), ('LOW', 'LOW'), ('EXEMPT_IMPORT_EXPORT', 'EXEMPT_IMPORT_EXPORT'), ('EXEMPT', 'EXEMPT'), ('OUTSIDE', 'OUTSIDE'), ('EXEMPT_REVERSE', 'EXEMPT_REVERSE')], default='NONE', max_length=200),
        ),
    ]
