# Generated by Django 3.2.12 on 2022-03-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("splash", "0001_initial"),
        ("splash", "0002_splashyear_start_date"),
        ("splash", "0003_auto_20150422_2218"),
        ("splash", "0004_auto_20150422_2234"),
        ("splash", "0005_auto_20150422_2236"),
        ("splash", "0006_auto_20151213_0309"),
        ("splash", "0007_auto_20160812_2053"),
        ("splash", "0008_auto_20160812_2053"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SplashEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("content", models.TextField(verbose_name="content")),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
            ],
            options={
                "ordering": ("start_time",),
                "abstract": False,
            },
        ),
    ]
