# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 18:53
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0006_auto_20151213_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splashevent',
            name='splash_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='splash_events', to='splash.SplashYear'),
        ),
    ]
