# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("splash", "0007_auto_20160812_2053")]

    operations = [
        migrations.RemoveField(model_name="splashevent", name="created"),
        migrations.RemoveField(model_name="splashevent", name="modified"),
        migrations.RemoveField(model_name="splashevent", name="splash_year"),
        migrations.DeleteModel(name="SplashYear"),
    ]
