# Generated by Django 2.0.13 on 2019-05-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0008_auto_20160812_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='splashevent',
            options={'default_permissions': ('add', 'change', 'delete'), 'ordering': ('start_time',)},
        ),
    ]
