# Generated by Django 2.1.11 on 2019-11-02 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0024_auto_20191010_2259"),
        ("splash", "0009_auto_20190506_1719"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudienceGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=64, verbose_name="Navn"),
                ),
            ],
            options={
                "verbose_name": "Deltakergruppe",
                "verbose_name_plural": "Deltakergrupper",
                "ordering": ("name",),
            },
        ),
        migrations.AlterModelOptions(
            name="splashevent",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("start_time",),
                "verbose_name": "Fadderukearrangement",
                "verbose_name_plural": "Fadderukearrangementer",
            },
        ),
        migrations.AddField(
            model_name="splashevent",
            name="event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="splash_event",
                to="events.Event",
                verbose_name="Arrangement",
            ),
        ),
        migrations.AlterField(
            model_name="splashevent",
            name="content",
            field=models.TextField(verbose_name="Innhold"),
        ),
        migrations.AlterField(
            model_name="splashevent",
            name="end_time",
            field=models.DateTimeField(verbose_name="Sluttid"),
        ),
        migrations.AlterField(
            model_name="splashevent",
            name="start_time",
            field=models.DateTimeField(verbose_name="Starttid"),
        ),
        migrations.AlterField(
            model_name="splashevent",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Tittel"),
        ),
        migrations.AddField(
            model_name="splashevent",
            name="target_audience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="splash_events",
                to="splash.AudienceGroup",
                verbose_name="Deltakergruppe",
            ),
        ),
    ]
