# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=250)),
                ('image', models.ImageField(upload_to='images/resourcecenter')),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
    ]
