# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resourcecenter", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="resource", name="description", field=models.TextField()
        ),
        migrations.AlterField(
            model_name="resource", name="title", field=models.CharField(max_length=35)
        ),
    ]
