# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-12 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourcecenter', '0002_auto_20170920_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='gallery.ResponsiveImage'),
        ),
    ]
