# Generated by Django 2.0.13 on 2019-05-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourcecenter', '0002_auto_20170920_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'default_permissions': ('add', 'change', 'delete')},
        ),
    ]
