# Generated by Django 2.1.8 on 2019-05-10 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourcecenter', '0003_auto_20190506_1719'),
        ('resourcecenter', '0004_resource_active'),
    ]

    operations = [
    ]
