# Generated by Django 2.1.8 on 2019-05-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourcecenter', '0007_resource_image'),
        ('resourcecenter', '0005_merge_20190510_0345'),
    ]

    operations = [
    ]
