# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genfors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='pin',
            field=models.CharField(default='stub', max_length=8, verbose_name='Pinkode'),
        ),
    ]
