# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genfors', '0003_question_count_blank_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='locked',
            field=models.BooleanField(default=False, help_text='Steng avstemmingen', verbose_name='låst'),
        ),
    ]
