# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-05 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careeropportunity', '0001_squashed_0003_auto_20151017_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='careeropportunity',
            name='job_type',
            field=models.IntegerField(choices=[(1, 'Fastjobb'), (2, 'Deltidsjobb'), (3, 'Sommerjobb/internship'), (4, 'Start-up'), (5, 'Annet')], default=5),
        ),
    ]
