# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-05 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careeropportunity', '0002_careeropportunity_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='careeropportunity',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='søknadsfrist'),
        ),
    ]
