# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-26 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("careeropportunity", "0003_careeropportunity_deadline"),
        ("careeropportunity", "0002_auto_20161019_2138"),
    ]

    operations = []
