# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-26 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("careeropportunity", "0005_auto_20161026_2110")]

    operations = [
        migrations.AddField(
            model_name="careeropportunity",
            name="employment",
            field=models.IntegerField(
                choices=[
                    (1, "Fastjobb"),
                    (2, "Deltidsjobb"),
                    (3, "Sommerjobb/internship"),
                    (4, "Start-up"),
                    (5, "Annet"),
                ],
                default=5,
                verbose_name="stillingstype",
            ),
        )
    ]
