# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-24 18:01
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('careeropportunity', '0006_careeropportunity_employment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careeropportunitylocationtag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='careeropportunitylocationtag',
            name='tag',
        ),
        migrations.AlterField(
            model_name='careeropportunity',
            name='location',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='sted(er)'),
        ),
        migrations.DeleteModel(
            name='CareerOpportunityLocationTag',
        ),
    ]
