# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("careeropportunity", "0009_auto_20171115_2208")]

    operations = [
        migrations.AlterField(
            model_name="careeropportunity",
            name="employment",
            field=models.IntegerField(
                choices=[
                    (1, "Fastjobb"),
                    (2, "Deltidsjobb"),
                    (3, "Sommerjobb/internship"),
                    (4, "Start-up"),
                    (5, "Annet"),
                ],
                verbose_name="stillingstype",
            ),
        )
    ]
