# Generated by Django 2.1 on 2019-04-03 19:32

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('careeropportunity', '0010_auto_20180424_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careeropportunity',
            options={'permissions': (('show_careeropportunity', 'Show CareerOpportunity'),), 'verbose_name': 'karrieremulighet', 'verbose_name_plural': 'karrieremuligheter'},
        ),
        migrations.AlterField(
            model_name='careeropportunity',
            name='featured',
            field=models.BooleanField(blank=True, default=False, verbose_name='fremhevet'),
        ),
        migrations.AlterField(
            model_name='careeropportunity',
            name='location',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='+', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='sted(er)'),
        ),
    ]
