# Generated by Django 2.0.13 on 2019-02-20 21:05

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('careeropportunity', '0010_auto_20180424_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careeropportunity',
            name='location',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='+', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='sted(er)'),
        ),
    ]
