# Generated by Django 3.0.5 on 2020-04-26 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companyprofile", "0007_company_created_date"),
        ("careeropportunity", "0014_auto_20191031_1239"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careeropportunity",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="career_opportunities",
                to="companyprofile.Company",
                verbose_name="Bedrift",
            ),
        )
    ]
