# Generated by Django 3.0.9 on 2020-10-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("careeropportunity", "0015_auto_20200426_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="careeropportunity",
            name="application_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="søknadsepost"
            ),
        ),
    ]
