# Generated by Django 5.1.1 on 2024-09-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("careeropportunity", "0017_careeropportunity_deadline_asap"),
    ]

    operations = [
        migrations.RenameField(
            model_name="careeropportunity",
            old_name="deadline_asap",
            new_name="rolling_admission",
        ),
        migrations.AlterField(
            model_name="careeropportunity",
            name="rolling_admission",
            field=models.BooleanField(
                default=False, verbose_name="Søknader vurderes fortløpende"
            ),
        ),
    ]
