# Generated by Django 5.1.1 on 2024-09-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("careeropportunity", "0017_careeropportunity_deadline_asap"),
    ]

    operations = [
        migrations.AddField(
            model_name="careeropportunity",
            name="rolling_admission",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Løpende opptak"
            ),
        ),
    ]
