# Generated by Django 5.1.1 on 2024-09-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("careeropportunity", "0018_careeropportunity_rolling_admission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careeropportunity",
            name="rolling_admission",
            field=models.BooleanField(default=False, verbose_name="Løpende opptak"),
        ),
    ]
