# Generated by Django 2.1 on 2019-04-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0005_auto_20150916_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={'permissions': (('show_mark', 'Show Mark'),), 'verbose_name': 'Prikk', 'verbose_name_plural': 'Prikker'},
        ),
    ]
