# Generated by Django 2.0.13 on 2019-05-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("marks", "0005_auto_20150916_2124")]

    operations = [
        migrations.AlterModelOptions(
            name="mark",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (("view_mark", "View Mark"),),
                "verbose_name": "Prikk",
                "verbose_name_plural": "Prikker",
            },
        ),
        migrations.AlterModelOptions(
            name="markuser",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("expiration_date",),
                "permissions": (("view_userentry", "View UserEntry"),),
            },
        ),
        migrations.AlterModelOptions(
            name="suspension",
            options={"default_permissions": ("add", "change", "delete")},
        ),
    ]
