# Generated by Django 5.0.5 on 2024-06-01 20:39

import datetime

from django.db import migrations, models

from ..models import Mark as MarkClass


def migrate_mark_category(apps, schema_editor):
    Mark = apps.get_model("marks", "Mark")
    marks = Mark.objects.iterator(chunk_size=50)
    for m in marks:
        for title, cause in [
            ("Prikk for Manglende oppmøte", MarkClass.Cause.NO_ATTENDANCE),
            ("Prikk for Manglende tilbakemelding", MarkClass.Cause.MISSED_FEEDBACK),
            ("Prikk for Manglende betaling", MarkClass.Cause.MISSED_PAYMENT),
            # the vast majority of others are due to late arrival, and some minor ones for behavior
        ]:
            if m.title.startswith(title):
                m.cause = cause

    Mark.objects.bulk_update(marks, ["cause"])


class Migration(migrations.Migration):
    dependencies = [
        ("marks", "0008_auto_20191009_1245"),
    ]

    operations = [
        migrations.AddField(
            model_name="mark",
            name="weight",
            field=models.SmallIntegerField(
                default=1,
                verbose_name="Vekting, for brukeren får du X antall prikker per 'Mark'",
            ),
        ),
        migrations.AlterField(
            model_name="mark",
            name="added_date",
            field=models.DateField(
                default=datetime.datetime.now, verbose_name="utdelt dato"
            ),
        ),
        migrations.AddField(
            model_name="mark",
            name="cause",
            field=models.CharField(
                choices=[
                    ("sen avmelding", "Avmelding etter avmeldingsfrist"),
                    (
                        "veldig sen avmelding",
                        "Avmelding under 2 timer før arrangementstart",
                    ),
                    (
                        "sent oppmøte",
                        "Oppmøte etter arrangementets start eller innslipp er ferdig",
                    ),
                    ("manglende oppmøte", "Manglende oppmøte"),
                    (
                        "manglende tilbakemelding",
                        "Svarte ikke på tilbakemeldingsskjema",
                    ),
                    ("manglende betaling", "Manglende betaling"),
                    ("annet", "Ukjent grunn"),
                ],
                default="annet",
                max_length=30,
                verbose_name="årsak",
            ),
        ),
        migrations.RunPython(migrate_mark_category),
    ]
