# Generated by Django 5.0.5 on 2024-06-06 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marks", "0009_mark_weight_alter_mark_added_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mark",
            name="users",
            field=models.ManyToManyField(
                related_name="marks",
                through="marks.MarkUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="suspension",
            name="cause",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Manglende betaling"),
                    (1, "For mange prikker på rad"),
                    (2, "Annet, se beskrivelse"),
                ],
                default=0,
                verbose_name="Årsak",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mark",
            name="weight",
            field=models.SmallIntegerField(
                verbose_name="Vekting, se prikkreglene for veiledning"
            ),
        ),
        migrations.AlterField(
            model_name="markuser",
            name="mark",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_to",
                to="marks.mark",
            ),
        ),
        migrations.AlterField(
            model_name="markuser",
            name="user",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="suspension",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suspensions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
