# Generated by Django 5.0.7 on 2024-07-23 20:48

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.marks.models


def set_mark_expiration_date(apps, schema_editor):
    Mark = apps.get_model("marks", "Mark")
    marks = list(Mark.objects.iterator(chunk_size=50))
    for m in marks:
        m.expiration_date = m.added_date + datetime.timedelta(days=20)

    Mark.objects.bulk_update(marks, ["expiration_date"])


class Migration(migrations.Migration):
    dependencies = [
        ("marks", "0010_mark_users_suspension_cause_alter_mark_weight_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mark",
            name="expiration_date",
            field=models.DateField(
                # dummy default, will be replaced in next step
                # we are moving expiration_date from markuser to mark
                # marks used to build on each other, but that is
                # no longer the case
                default=django.utils.timezone.datetime(1990, 1, 1),
                verbose_name="Utløpsdato",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_mark_expiration_date),
        migrations.RemoveField(
            model_name="suspension",
            name="active",
        ),
        migrations.RenameField(
            model_name="suspension",
            old_name="added_date",
            new_name="created_time",
        ),
        migrations.AlterField(
            model_name="suspension",
            name="created_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="markruleset",
            name="duration",
            field=models.DurationField(
                default=datetime.timedelta(days=20), verbose_name="Varighet på prikker"
            ),
        ),
        migrations.AddField(
            model_name="mark",
            name="ruleset",
            field=models.ForeignKey(
                default=apps.marks.models.MarkRuleSet.get_current_rule_set_pk,
                on_delete=django.db.models.deletion.CASCADE,
                to="marks.markruleset",
            ),
        ),
        migrations.AddField(
            model_name="markruleset",
            name="acceptors",
            field=models.ManyToManyField(
                through="marks.RuleAcceptance", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="mark",
            name="added_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="utdelt dato"
            ),
        ),
        migrations.AlterField(
            model_name="mark",
            name="given_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mark_given_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="gitt av",
            ),
        ),
        migrations.AlterField(
            model_name="mark",
            name="last_changed_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marks_last_changed_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="sist redigert av",
            ),
        ),
        migrations.AlterField(
            model_name="markuser",
            name="expiration_date",
            field=models.DateField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                verbose_name="utløpsdato",
            ),
        ),
        migrations.AlterField(
            model_name="suspension",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
