# Generated by Django 5.0.7 on 2024-08-02 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marks", "0013_alter_mark_expiration_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="suspension",
            options={
                "default_permissions": ("add", "change", "delete"),
                "verbose_name": "Suspensjoner",
            },
        ),
    ]
