# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-09 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Tittel'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='uploaded_media/images/photo_album'),
        ),
    ]
