# Generated by Django 2.1.11 on 2019-09-30 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photoalbum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'default_permissions': ('add', 'change', 'delete'), 'ordering': ('album', 'timestamp'), 'permissions': (('view_responsiveimage', 'View ResponsiveImage'),), 'verbose_name': 'Bilde', 'verbose_name_plural': 'Bilder'},
        ),
        migrations.AlterModelOptions(
            name='usertag',
            options={'ordering': ('photo', 'created_date', 'user'), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tagger'},
        ),
        migrations.AlterField(
            model_name='album',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_albums', to=settings.AUTH_USER_MODEL, verbose_name='Oppretted av'),
        ),
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together={('album', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='usertag',
            unique_together={('user', 'photo')},
        ),
    ]
