# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-09 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0002_auto_20180109_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='photoalbum.Album'),
            preserve_default=False,
        ),
    ]
