# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0004_auto_20180207_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(to='photoalbum.Photo'),
        ),
    ]
