# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photoalbum', '0005_auto_20180207_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tagged_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
