# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 18:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photoalbum', '0006_photo_tagged_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumToPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoWithUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='tagged_users',
        ),
        migrations.AddField(
            model_name='photowithuser',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoalbum.Photo'),
        ),
        migrations.AddField(
            model_name='photowithuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='albumtophoto',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoalbum.Album'),
        ),
        migrations.AddField(
            model_name='albumtophoto',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoalbum.Photo'),
        ),
    ]
