# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0007_auto_20180207_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsToAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoalbum.Album')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoalbum.AlbumTag')),
            ],
        ),
    ]
