# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0008_tagstoalbum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoWithUser',
            new_name='UserTagToPhoto',
        ),
    ]
