# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("feedback", "0008_auto_20160906_1703")]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="display_field_of_study",
            field=models.BooleanField(
                default=True,
                help_text="Grafen over studiefelt vil bli vist til bedriften",
                verbose_name="Vis studieoversikt",
            ),
        )
    ]
