# Generated by Django 2.1 on 2019-04-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_auto_20180424_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'permissions': (('show_choice', 'Show Choice'),)},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'permissions': (('show_feedback', 'Show Feedback'),), 'verbose_name': 'tilbakemeldingsskjema', 'verbose_name_plural': 'tilbakemeldingsskjemaer'},
        ),
        migrations.AlterModelOptions(
            name='feedbackrelation',
            options={'permissions': (('show_feedbackrelation', 'Show FeedbackRelation'),), 'verbose_name': 'tilbakemelding', 'verbose_name_plural': 'tilbakemeldinger'},
        ),
        migrations.AlterModelOptions(
            name='fieldofstudyanswer',
            options={'permissions': (('show_fieldofstudyanswer', 'Show FieldOfStudyAnswer'),)},
        ),
        migrations.AlterModelOptions(
            name='multiplechoiceanswer',
            options={'permissions': (('show_multiplechoiceanswer', 'Show MultipleChoiceAnswer'),)},
        ),
        migrations.AlterModelOptions(
            name='multiplechoicequestion',
            options={'permissions': (('show_multiplechoicequestion', 'Show MultipleChoiceQuestion'),), 'verbose_name': 'Flervalgspørsmål', 'verbose_name_plural': 'Flervalgspørsmål'},
        ),
        migrations.AlterModelOptions(
            name='multiplechoicerelation',
            options={'permissions': (('show_multiplechoicerelation', 'Show MultipleChoiceRelation'),)},
        ),
        migrations.AlterModelOptions(
            name='ratinganswer',
            options={'permissions': (('show_ratinganswer', 'Show RatingAnswer'),)},
        ),
        migrations.AlterModelOptions(
            name='ratingquestion',
            options={'permissions': (('show_ratingquestion', 'Show RatingQuestion'),)},
        ),
        migrations.AlterModelOptions(
            name='registertoken',
            options={'permissions': (('show_feedbackregistertoken', 'Show FeedbackRegisterToken'),)},
        ),
        migrations.AlterModelOptions(
            name='textanswer',
            options={'permissions': (('show_textanswer', 'Show TextAnswer'),)},
        ),
        migrations.AlterModelOptions(
            name='textquestion',
            options={'permissions': (('show_textquestion', 'Show TextQuestion'),)},
        ),
        migrations.AlterField(
            model_name='fieldofstudyanswer',
            name='answer',
            field=models.SmallIntegerField(choices=[(0, 'Gjest'), (1, 'Bachelor i Informatikk'), (10, 'Programvaresystemer'), (11, 'Databaser og søk'), (12, 'Algoritmer og datamaskiner'), (13, 'Spillteknologi'), (14, 'Kunstig intelligens'), (15, 'Helseinformatikk'), (16, 'Interaksjonsdesign, spill- og læringsteknologi'), (30, 'Annen mastergrad'), (40, 'Sosialt medlem'), (80, 'PhD'), (90, 'International'), (100, 'Annet Onlinemedlem')], verbose_name='Studieretning'),
        ),
    ]
