# Generated by Django 2.0.13 on 2019-02-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_auto_20190227_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='available',
            field=models.BooleanField(default=True, help_text='Dette brukes til å skjule ubrukte skjemaer, lager du et nytt, så ignorer denne.', verbose_name='Vis feedbackskjemaet'),
        ),
    ]
