# Generated by Django 2.1.11 on 2020-01-31 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0009_alter_user_last_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0013_auto_20190506_2241"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericSurvey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="Tittel")),
                ("deadline", models.DateField(verbose_name="Tidsfrist")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Opprettet dato"
                    ),
                ),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="allowed_generic_surveys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Brukere som kan svare",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generic_survey",
                        to="feedback.Feedback",
                        verbose_name="Undersøkelsesmal",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="owned_generic_surveys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eier",
                    ),
                ),
                (
                    "owner_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_generic_surveys",
                        to="auth.Group",
                        verbose_name="Eiergruppe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generisk undersøkelse",
                "verbose_name_plural": "Generiske undersøkelser",
                "ordering": ("created_date", "title"),
            },
        ),
        migrations.AlterModelOptions(
            name="choice",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (("view_choice", "View Choice"),),
                "verbose_name": "Valg",
                "verbose_name_plural": "Valg",
            },
        ),
        migrations.AlterModelOptions(
            name="fieldofstudyanswer",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (
                    ("view_fieldofstudyanswer", "View FieldOfStudyAnswer"),
                ),
                "verbose_name": "Studieretningssvar",
                "verbose_name_plural": "Studieretningssvar",
            },
        ),
        migrations.AlterModelOptions(
            name="multiplechoiceanswer",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (
                    ("view_multiplechoiceanswer", "View MultipleChoiceAnswer"),
                ),
                "verbose_name": "Flervalgssvar",
                "verbose_name_plural": "Flervalgssvar",
            },
        ),
        migrations.AlterModelOptions(
            name="multiplechoicerelation",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (
                    ("view_multiplechoicerelation", "View MultipleChoiceRelation"),
                ),
                "verbose_name": "Flervalgsrelasjon",
                "verbose_name_plural": "Flervalgsrelasjoner",
            },
        ),
        migrations.AlterModelOptions(
            name="ratinganswer",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (("view_ratinganswer", "View RatingAnswer"),),
                "verbose_name": "Vurderingssvar",
                "verbose_name_plural": "Vurderingssvar",
            },
        ),
        migrations.AlterModelOptions(
            name="ratingquestion",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (("view_ratingquestion", "View RatingQuestion"),),
                "verbose_name": "Vurderingsspørsmål",
                "verbose_name_plural": "Vurderingsspørsmål",
            },
        ),
        migrations.AlterModelOptions(
            name="textanswer",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (("view_textanswer", "View TextAnswer"),),
                "verbose_name": "Tekstsvar",
                "verbose_name_plural": "Tekstsvar",
            },
        ),
        migrations.AlterModelOptions(
            name="textquestion",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (("view_textquestion", "View TextQuestion"),),
                "verbose_name": "Tekstspørsmål",
                "verbose_name_plural": "Tekstspørsmål",
            },
        ),
        migrations.RenameField(
            model_name="multiplechoicerelation",
            old_name="multiple_choice_relation",
            new_name="question",
        ),
        migrations.AddField(
            model_name="registertoken",
            name="token_uuid",
            field=models.UUIDField(
                null=True, editable=False, unique=True, verbose_name="Token"
            ),
        ),
        migrations.AlterField(
            model_name="registertoken",
            name="fbr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="token_objects",
                to="feedback.FeedbackRelation",
            ),
        ),
    ]
