# Generated by Django 2.1.11 on 2019-11-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("feedback", "0013_auto_20190506_2241")]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (("view_choice", "View Choice"),),
                "verbose_name": "Valg",
                "verbose_name_plural": "Valg",
            },
        ),
        migrations.AlterModelOptions(
            name="fieldofstudyanswer",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (
                    ("view_fieldofstudyanswer", "View FieldOfStudyAnswer"),
                ),
                "verbose_name": "Studieretningssvar",
                "verbose_name_plural": "Studieretningssvar",
            },
        ),
        migrations.AlterModelOptions(
            name="multiplechoiceanswer",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (
                    ("view_multiplechoiceanswer", "View MultipleChoiceAnswer"),
                ),
                "verbose_name": "Flervalgssvar",
                "verbose_name_plural": "Flervalgssvar",
            },
        ),
        migrations.AlterModelOptions(
            name="multiplechoicerelation",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (
                    ("view_multiplechoicerelation", "View MultipleChoiceRelation"),
                ),
                "verbose_name": "Flervalgsrelasjon",
                "verbose_name_plural": "Flervalgsrelasjoner",
            },
        ),
        migrations.AlterModelOptions(
            name="ratinganswer",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (("view_ratinganswer", "View RatingAnswer"),),
                "verbose_name": "Vurderingssvar",
                "verbose_name_plural": "Vurderingssvar",
            },
        ),
        migrations.AlterModelOptions(
            name="ratingquestion",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (("view_ratingquestion", "View RatingQuestion"),),
                "verbose_name": "Vurderingsspørsmål",
                "verbose_name_plural": "Vurderingsspørsmål",
            },
        ),
        migrations.AlterModelOptions(
            name="textanswer",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (("view_textanswer", "View TextAnswer"),),
                "verbose_name": "Tekstsvar",
                "verbose_name_plural": "Tekstsvar",
            },
        ),
        migrations.AlterModelOptions(
            name="textquestion",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (("view_textquestion", "View TextQuestion"),),
                "verbose_name": "Tekstspørsmål",
                "verbose_name_plural": "Tekstspørsmål",
            },
        ),
    ]
