# Generated by Django 2.1.11 on 2019-10-27 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0013_auto_20190506_2241"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "feedback_relation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="feedback.FeedbackRelation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("created_date",)},
        ),
        migrations.AddField(
            model_name="fieldofstudyanswer",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="field_of_study_answers",
                to="feedback.Session",
            ),
        ),
        migrations.AddField(
            model_name="multiplechoiceanswer",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="multiple_choice_answers",
                to="feedback.Session",
            ),
        ),
        migrations.AddField(
            model_name="ratinganswer",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rating_answers",
                to="feedback.Session",
            ),
        ),
        migrations.AddField(
            model_name="textanswer",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="text_answers",
                to="feedback.Session",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="session", unique_together={("user", "feedback_relation")}
        ),
    ]
