# Generated by Django 2.1.11 on 2020-01-31 13:55

from django.db import migrations
import uuid


def forward(apps, schema_editor):
    RegisterToken = apps.get_model("feedback", "RegisterToken")

    for token_object in RegisterToken.objects.all():
        uuid_object = uuid.UUID(token_object.token)
        token_object.token_uuid = uuid_object
        token_object.save()


def backward(apps, schema_editor):
    RegisterToken = apps.get_model("feedback", "RegisterToken")

    for token_object in RegisterToken.objects.all():
        uuid_str = token_object.token_uuid.hex
        token_object.token = uuid_str
        token_object.save()


class Migration(migrations.Migration):

    dependencies = [("feedback", "0014_auto_20200131_1453")]

    operations = [migrations.RunPython(forward, backward)]
