# Generated by Django 2.1.11 on 2019-12-01 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0009_alter_user_last_name_max_length"),
        ("feedback", "0015_auto_20191117_1657"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericSurvey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="Tittel")),
                ("deadline", models.DateField(verbose_name="Tidsfrist")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Opprettet dato"
                    ),
                ),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        related_name="allowed_generic_surveys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Brukere som kan svare",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generic_survey",
                        to="feedback.Feedback",
                        verbose_name="Undersøkelsesmal",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="owned_generic_surveys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eier",
                    ),
                ),
                (
                    "owner_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_generic_surveys",
                        to="auth.Group",
                        verbose_name="Eiergruppe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generisk undersøkelse",
                "verbose_name_plural": "Generiske undersøkelser",
                "ordering": ("created_date", "title"),
            },
        )
    ]
