# Generated by Django 2.1.11 on 2020-01-31 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("feedback", "0015_auto_20200131_1455")]

    operations = [
        migrations.AlterField(
            model_name="registertoken",
            name="token_uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="Token"
            ),
        )
    ]
