# Generated by Django 2.1.11 on 2019-12-01 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("feedback", "0016_genericsurvey")]

    operations = [
        migrations.AlterField(
            model_name="genericsurvey",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="allowed_generic_surveys",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Brukere som kan svare",
            ),
        )
    ]
