# Generated by Django 2.1.11 on 2020-02-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("feedback", "0016_auto_20200131_1714")]

    operations = [migrations.RemoveField(model_name="registertoken", name="token")]
