# Generated by Django 2.1.11 on 2019-12-17 09:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [("feedback", "0017_auto_20191201_1619")]

    operations = [
        migrations.AlterField(
            model_name="registertoken",
            name="fbr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="token_objects",
                to="feedback.FeedbackRelation",
            ),
        ),
        migrations.AlterField(
            model_name="registertoken",
            name="token",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="Token"
            ),
        ),
    ]
