# Generated by Django 2.1.11 on 2020-02-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("feedback", "0017_remove_registertoken_token")]

    operations = [
        migrations.RenameField(
            model_name="registertoken", old_name="token_uuid", new_name="token"
        )
    ]
