# Generated by Django 3.0.6 on 2020-05-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0019_auto_20200206_2021"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedbackrelation",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("content_type", "object_id", "feedback"),
                "permissions": (("view_feedbackrelation", "View FeedbackRelation"),),
                "verbose_name": "tilbakemelding",
                "verbose_name_plural": "tilbakemeldinger",
            },
        ),
    ]
