# Generated by Django 3.0.6 on 2020-05-25 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0020_auto_20200525_1421"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fieldofstudyanswer",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("pk",),
                "permissions": (
                    ("view_fieldofstudyanswer", "View FieldOfStudyAnswer"),
                ),
                "verbose_name": "Studieretningssvar",
                "verbose_name_plural": "Studieretningssvar",
            },
        ),
        migrations.AlterModelOptions(
            name="textquestion",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("pk",),
                "permissions": (("view_textquestion", "View TextQuestion"),),
                "verbose_name": "Tekstspørsmål",
                "verbose_name_plural": "Tekstspørsmål",
            },
        ),
    ]
