# Generated by Django 3.2.18 on 2023-03-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0021_auto_20200525_1506"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackrelation",
            name="gives_mark",
            field=models.BooleanField(
                default=False,
                help_text="Gir automatisk prikk til brukere som ikke har svart innen fristen",
                verbose_name="Gir Prikk",
            ),
        ),
    ]
