# Generated by Django 2.1 on 2019-04-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offline', '0002_auto_20170124_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-release_date'], 'permissions': (('show_issue', 'Show Issue'),), 'verbose_name': 'Utgivelse', 'verbose_name_plural': 'Utgivelser'},
        ),
    ]
