# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-03 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20171106_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='low_stock_treshhold',
            field=models.IntegerField(default=10, verbose_name='Grense for email om lav beholdning'),
        ),
    ]
