# Generated by Django 2.1 on 2019-04-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_batch_low_stock_treshhold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': (('show_item', 'Show Inventory Item'),), 'verbose_name': 'Vare', 'verbose_name_plural': 'Varer'},
        ),
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'permissions': (('show_itemcategory', 'Show Item Category'),), 'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategorier'},
        ),
    ]
