# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-03 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_batch_low_stock_treshhold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='low_stock_treshhold',
        ),
        migrations.AddField(
            model_name='item',
            name='low_stock_treshhold',
            field=models.IntegerField(default=10, verbose_name='Grense for email om lav beholdning'),
        ),
    ]
