# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-03 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20181003_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='low_stock_treshhold',
            new_name='low_stock_treshold',
        ),
    ]
