# Generated by Django 5.0.4 on 2024-04-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_auto_20190506_1719"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="category",
        ),
        migrations.RemoveField(
            model_name="item",
            name="image",
        ),
        migrations.DeleteModel(
            name="Batch",
        ),
        migrations.DeleteModel(
            name="ItemCategory",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
