# Generated by Django 3.2.23 on 2023-11-03 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0050_alter_onlineuser_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='melding')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Opprettet dato')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Oppdatert dato')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_update', to='authentication.onlinegroup', verbose_name='Forfatter gruppe')),
            ],
        ),
    ]
