# Generated by Django 2.1 on 2019-04-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20160309_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsiveimage',
            options={'permissions': (('show_responsiveimage', 'Show ResponsiveImage'),), 'verbose_name': 'Responsivt Bilde', 'verbose_name_plural': 'Responsive Bilder'},
        ),
        migrations.AlterModelOptions(
            name='unhandledimage',
            options={'permissions': (('show_unhandledimage', 'Show UnhandledImage'),), 'verbose_name': 'Ubehandlet bilde', 'verbose_name_plural': 'Ubehandlede bilder'},
        ),
    ]
