# Generated by Django 3.0.5 on 2020-05-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0013_auto_20190506_1719"),
    ]

    operations = [
        migrations.AddField(
            model_name="responsiveimage",
            name="format",
            field=models.CharField(
                choices=[
                    ("article", "Artikkel"),
                    ("company", "Bedriftslogo"),
                    ("event", "Arrangement"),
                    ("offline", "Offline"),
                    ("photoalbum", "Fotoalbum"),
                    ("product", "Produktbilde"),
                    ("resource", "Ressurs"),
                    ("group", "Gruppe"),
                ],
                default="event",
                max_length=128,
                verbose_name="Format",
            ),
            preserve_default=False,
        ),
    ]
