# Generated by Django 3.0.5 on 2020-05-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0014_responsiveimage_format"),
    ]

    operations = [
        migrations.RenameField(
            model_name="responsiveimage",
            old_name="format",
            new_name="preset",
        ),
    ]
