# Generated by Django 3.2.9 on 2021-11-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0015_auto_20200505_1141"),
    ]

    operations = [
        migrations.AddField(
            model_name="unhandledimage",
            name="height",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="unhandledimage",
            name="size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="unhandledimage",
            name="thumbnailSize",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="unhandledimage",
            name="width",
            field=models.IntegerField(default=0),
        ),
    ]
