# Generated by Django 3.2.9 on 2021-11-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0016_auto_20211118_1828"),
    ]

    operations = [
        migrations.AddField(
            model_name="responsiveimage",
            name="total_size",
            field=models.IntegerField(default=0),
        ),
    ]
