# Generated by Django 2.0.13 on 2019-02-26 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shop", "0003_magictoken")]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        )
    ]
