# Generated by Django 2.0.13 on 2019-05-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_auto_20190506_1719"),
        ("shop", "0004_auto_20190226_1239"),
    ]

    operations = []
