# Generated by Django 2.2.10 on 2020-03-06 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0035_auto_20200307_1530"),
        ("shop", "0006_auto_20200229_1046"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop_order_line",
                to="payment.PaymentTransaction",
                verbose_name="Transaksjon",
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Tidspunkt"),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="Betalt"),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_order_lines",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bruker",
            ),
        ),
    ]
