# Generated by Django 2.2.10 on 2020-03-07 14:37

from django.db import migrations


def load_data(apps, schema_editor):
    OrderLine = apps.get_model("shop", "OrderLine")
    PaymentTransaction = apps.get_model("payment", "PaymentTransaction")

    for order_line in OrderLine.objects.all():
        subtotal = 0
        for order in order_line.orders.all():
            total_price = order.price
            subtotal += total_price

        transaction = PaymentTransaction.objects.create(
            # The only currency available at this point
            source="shop",
            amount=-subtotal,
            user=order_line.user,
            datetime=order_line.datetime,
            # These order_lines are already registered in each users wallet
            status="done",
            # Receipts should not be sent for transactions which are already completed
            create_receipt=False,
            shop_order_line=order_line,
        )
        order_line.transaction = transaction
        order_line.save()
        transaction.save()
        transaction.refresh_from_db()
        if transaction.shop_order_line != order_line:
            raise ValueError("Fuck this")


def remove_data(apps, schema_editor):
    PaymentTransaction = apps.get_model("payment", "PaymentTransaction")
    PaymentTransaction.objects.filter(source="shop").delete()


class Migration(migrations.Migration):
    dependencies = [("shop", "0007_auto_20200306_2144")]

    operations = [migrations.RunPython(load_data, remove_data)]
