# Generated by Django 5.0.4 on 2024-04-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_auto_20200307_1537"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_line",
        ),
        migrations.RemoveField(
            model_name="orderline",
            name="transaction",
        ),
        migrations.RemoveField(
            model_name="orderline",
            name="user",
        ),
        migrations.DeleteModel(
            name="MagicToken",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderLine",
        ),
    ]
