# Generated by Django 3.0.6 on 2020-05-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_auto_20200307_1537"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderline",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("-datetime", "-transaction"),
            },
        ),
    ]
