# Generated by Django 2.2.10 on 2020-02-29 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("posters", "0007_auto_20190506_1719")]

    operations = [
        migrations.AlterField(
            model_name="ordermixin",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_posters",
                to=settings.AUTH_USER_MODEL,
                verbose_name="tilordnet til",
            ),
        ),
        migrations.AlterField(
            model_name="ordermixin",
            name="ordered_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordered_posters",
                to=settings.AUTH_USER_MODEL,
                verbose_name="bestilt av",
            ),
        ),
        migrations.AlterField(
            model_name="ordermixin",
            name="ordered_committee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordered_posters",
                to="auth.Group",
                verbose_name="bestilt av komité",
            ),
        ),
        migrations.AlterField(
            model_name="poster",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poster_orders",
                to="events.Event",
                verbose_name="Arrangement",
            ),
        ),
    ]
