# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-28 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=250)),
                ('image', models.ImageField(upload_to='images/hobbygroups')),
                ('read_more_link', models.URLField(blank=True)),
            ],
        ),
    ]
