# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-07 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbygroups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='hobby_priority',
            field=models.IntegerField(default=0),
        ),
    ]
