# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-04 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobbygroups', '0002_hobby_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hobbys', to='gallery.ResponsiveImage'),
        ),
    ]
