# Generated by Django 1.11.3 on 2018-08-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("hobbygroups", "0002_hobby_priority")]

    operations = [
        migrations.AlterField(
            model_name="hobby",
            name="description",
            field=models.TextField(max_length=300),
        )
    ]
