# Generated by Django 2.0.13 on 2019-04-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobbygroups', '0004_auto_20190130_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hobbies', to='gallery.ResponsiveImage'),
        ),
    ]
