# Generated by Django 2.1.8 on 2019-05-10 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbygroups', '0005_auto_20190506_1719'),
    ]

    operations = [
    ]
