# Generated by Django 2.1.8 on 2019-05-10 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_auto_20190506_1719'),
        ('hobbygroups', '0007_remove_hobby_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hobbies', to='gallery.ResponsiveImage'),
        ),
    ]
