# Generated by Django 2.1.8 on 2019-05-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbygroups', '0008_hobby_image'),
        ('hobbygroups', '0006_merge_20190510_0346'),
    ]

    operations = [
    ]
