# Generated by Django 2.0.13 on 2019-05-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("article", "0010_auto_20151101_0522")]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ["published_date"],
                "permissions": (("view_article", "View Article"),),
                "verbose_name": "artikkel",
                "verbose_name_plural": "artikler",
            },
        )
    ]
