# Generated by Django 2.1 on 2019-04-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20151101_0522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['published_date'], 'permissions': (('show_article', 'Show Article'),), 'verbose_name': 'artikkel', 'verbose_name_plural': 'artikler'},
        ),
    ]
