# Generated by Django 2.1.11 on 2019-10-07 21:57

import apps.article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("article", "0011_auto_20190506_1719")]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="video",
            field=models.CharField(
                blank=True,
                max_length=200,
                validators=[apps.article.models.vimeo_id_validator],
                verbose_name="vimeo id",
            ),
        )
    ]
