# Generated by Django 2.2.10 on 2020-02-29 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("article", "0012_auto_20191007_2357")]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_articles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="opprettet av",
            ),
        )
    ]
