import os

from decouple import config

OW4_FIKEN_ORG = config('OW4_FIKEN_ORG', default='')
OW4_FIKEN_USER = config('OW4_FIKEN_USER', default='')
OW4_FIKEN_PASSWORD = config('OW4_FIKEN_PASSWORD', default='')

OW4_FIKEN_ACCOUNT_ARRKOM = config('OW4_FIKEN_ACCOUNT_ARRKOM', default='')
OW4_FIKEN_ACCOUNT_PROKOM = config('OW4_FIKEN_ACCOUNT_PROKOM', default='')
OW4_FIKEN_ACCOUNT_TRIKOM = config('OW4_FIKEN_ACCOUNT_TRIKOM', default='')
OW4_FIKEN_ACCOUNT_FAGKOM = config('OW4_FIKEN_ACCOUNT_FAGKOM', default='')

OW4_FIKEN_ACCOUNT_SALES_MEDALS = config('OW4_FIKEN_ACCOUNT_SALES_MEDALS', default='')
OW4_FIKEN_ACCOUNT_SALES_EXEMPT = config('OW4_FIKEN_ACCOUNT_SALES_EXEMPT', default='')
OW4_FIKEN_ACCOUNT_SALES_NONE = config('OW4_FIKEN_ACCOUNT_SALES_NONE', default='')
OW4_FIKEN_ACCOUNT_SERVICES = config('OW4_FIKEN_ACCOUNT_SERVICES', default='')
OW4_FIKEN_ACCOUNT_SUBSCRIPTIONS_OFFLINE = config('OW4_FIKEN_ACCOUNT_SUBSCRIPTIONS_OFFLINE', default='')
OW4_FIKEN_ACCOUNT_SALES_NIBBLE = config('OW4_FIKEN_ACCOUNT_SALES_NIBBLE', default='')
OW4_FIKEN_ACCOUNT_ATTENDEES_ARRKOM = config('OW4_FIKEN_ACCOUNT_ATTENDEES_ARRKOM', default='')
OW4_FIKEN_ACCOUNT_ATTENDEES_GALLA = config('OW4_FIKEN_ACCOUNT_ATTENDEES_GALLA', default='')
OW4_FIKEN_ACCOUNT_ATTENDEES_GRADUATION = config('OW4_FIKEN_ACCOUNT_ATTENDEES_GRADUATION', default='')
OW4_FIKEN_ACCOUNT_ATTENDEES_ARE = config('OW4_FIKEN_ACCOUNT_ATTENDEES_ARE', default='')

OW4_FIKEN_FILE_ROOT = config('OW4_FIKEN_FILE_ROOT', default=os.path.join('files', 'fiken', 'attachments'))
