# -*- coding: utf-8 -*-

from django.shortcuts import render
from memcache import Client

# dotKom: To manually see the mailinglists in memcache, do this:
#
# $ ssh you@morgan.online.ntnu.no               # connect to morgan
# $ sudo su www-data -                          # log in as web user
# $ python                                      # open the interactive python shell
# $ from memcache import client                 # error message will appear if the library is not found
# $ mc = Client(["127.0.0.1:11211"], debug=0)   # start the memcache client
# $ lists = mc.get("sympa_lists")               # get sympa lists that are stored in memcache
# $ print lists


def index(request):


    # If we couldn't find any information in memcache right now

    lists = [
        {'name': 'linjeforeninger', 'members': [
            {'name': 'Dragvoll', 'email': 'dragvoll@online.ntnu.no'},
            {'name': 'Gløshaugen', 'email': 'gloshaugen@online.ntnu.no'},
            {'name': 'Kalvskinnet', 'email': 'kalvskinnet@online.ntnu.no'},

            # All old lists have been saved for double checking

            # {'subscriber': '', 'name': 'Alf', 'email': 'alf-styret@list.stud.ntnu.no'},
            # {'subscriber': '', 'name': 'Smørekoppen', 'email': 'styret@smorekoppen.no'},
            # {'subscriber': '', 'name': 'Abakus', 'email': 'abakus@abakus.no'},
            # {'subscriber': '', 'name': 'Omega', 'email': 'omega@omega.ntnu.no'},
            # {'subscriber': '', 'name': 'Bergstuderendes Forening', 'email': 'bsf@org.ntnu.no'},
            # {'subscriber': '', 'name': 'Delta', 'email': 'delta@list.stud.ntnu.no'},
            # {'subscriber': '', 'name': 'Aarhønen', 'email': 'hs@aarhonen.no'},
            # {'subscriber': '', 'name': 'Hybrida', 'email': 'hybrida@org.ntnu.no'},
            # {'subscriber': '', 'name': 'Janus', 'email': 'janus@org.ntnu.no'},
            # {'subscriber': '', 'name': 'Online', 'email': 'online@online.ntnu.no'},
            # {'subscriber': '', 'name': 'Placebo', 'email': 'placebo@list.stud.ntnu.no'},
            # {'subscriber': '', 'name': 'Spanskrøret', 'email': 'styre@spanskroret.no'},
            # {'subscriber': '', 'name': 'HC', 'email': 'styret@hc.ntnu.no'},
            # {'subscriber': '', 'name': 'Mannhullet', 'email': 'styret@mannhullet.no'},
            # {'subscriber': '', 'name': 'Volvox', 'email': 'volvox-styre@list.stud.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Socius Extremus', 'email': 'socius.extremus@hotmail.no'},
            # {'subscriber': '', 'name': 'Nabla', 'email': 'nabla@nabla.ntnu.no'},
            # {'subscriber': '', 'name': 'Leonardo', 'email': 'leonardo-styret@list.stud.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Erudio', 'email': 'erudiostyret@hotmail.com'},
            # {'subscriber': 'mail', 'name': 'Paideia', 'email': 'paideia@live.no'},
            # {'subscriber': 'mail', 'name': 'CAF', 'email': 'idrett@hotmail.com'},
            # {'subscriber': 'mail', 'name': 'ELF', 'email': 'ntnuelf@gmail.com'},
            # {'subscriber': 'mail', 'name': 'PSI', 'email': 'psi.linjeforening@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Katharsis', 'email': 'linjeforeningenkatharsis@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Geolf', 'email': 'info.geolf@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Ludimus', 'email': 'ludimus@list.stud.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'De Passe Simple', 'email': 'depassesimple@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Eureka', 'email': 'eurekalinjeforening@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Sturm Und Drang', 'email': 'sturmunddrang.ntnu@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Theodor', 'email': 'theodor.arkeologi@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Kwakiutl', 'email': 'sosant.ntnu@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Primetime', 'email': 'primetime.ntnu@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Akwaaba', 'email': 'akwaabapost.ntnu@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Jump Cut', 'email': 'jumpcut.dragvoll@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Panoptikon', 'email': 'tverrfagligkult@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Kultura', 'email': 'kulturalinjeforening@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Gengangere', 'email': 'gengangere@list.stud.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Pareto', 'email': 'pareto.linjeforening@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Dionysos', 'email': 'dionysoslinjeforening@gmail.com'},
            # {'subscriber': 'mail', 'name': 'De Folkevalgte', 'email': 'defolkevalgte@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Apeiron', 'email': 'apeiron.ntnu@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Psykolosjen', 'email': 'psykolosjen@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Det Historiske Selskab', 'email': 'ntnu_dhs@hotmail.com'},
            # {'subscriber': '', 'name': 'Timini', 'email': 'styret@timini.no'},
            # {'subscriber': 'mail', 'name': 'LiMP', 'email': 'linjeforeningen.limp@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Ivrig', 'email': 'ivrig.linjeforening@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Emil', 'email': 'styret@emilweb.no'},
            # {'subscriber': 'mail', 'name': 'Solan', 'email': 'solan@entreprenorskolen.no'},
            # {'subscriber': 'mail', 'name': 'Teaterlosjen', 'email': 'teaterlosjen@gmail.com'}
        ]},
        {'name': 'dragvoll', 'members': [
            {'name': 'FINDNAME', 'email': 'akwaabapost.ntnu@gmail.com'},
            {'name': 'FINDNAME', 'email': 'apeiron.ntnu@gmail.com'},
            {'name': 'FINDNAME', 'email': 'cafidrett@gmail.com'},
            {'name': 'FINDNAME', 'email': 'defolkevalgte@gmail.com'},
            {'name': 'FINDNAME', 'email': 'depassesimple@gmail.com'},
            {'name': 'FINDNAME', 'email': 'dionysoslinjeforening@gmail.com'},
            {'name': 'FINDNAME', 'email': 'eurekalinjeforening@gmail.com'},
            {'name': 'FINDNAME', 'email': 'faureningen@gmail.com'},
            {'name': 'FINDNAME', 'email': 'gengangere@list.stud.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'hf@studentrad.no'},
            {'name': 'FINDNAME', 'email': 'hs@teaterlosjen.no'},
            {'name': 'FINDNAME', 'email': 'info.geolf@gmail.com'},
            {'name': 'FINDNAME', 'email': 'ivrig.linjeforening@gmail.com'},
            {'name': 'FINDNAME', 'email': 'jumpcut.dragvoll@gmail.com'},
            {'name': 'FINDNAME', 'email': 'kulturalinjeforening@gmail.com'},
            {'name': 'FINDNAME', 'email': 'linjeforeningenlimp@gmail.com'},
            {'name': 'FINDNAME', 'email': 'liptonlinjeforening@gmail.com'},
            {'name': 'FINDNAME', 'email': 'loselegidoslinjeforening@gmail.com'},
            {'name': 'FINDNAME', 'email': 'ntnu_dhs@hotmail.com'},
            {'name': 'FINDNAME', 'email': 'paideiantnu@gmail.com'},
            {'name': 'FINDNAME', 'email': 'pareto.linjeforening@gmail.com'},
            {'name': 'FINDNAME', 'email': 'post.detgyldnesnitt@gmail.com'},
            {'name': 'FINDNAME', 'email': 'primetime.ntnu@gmail.com'},
            {'name': 'FINDNAME', 'email': 'psi.linjeforening@gmail.com'},
            {'name': 'FINDNAME', 'email': 'psykolosjen@gmail.com'},
            {'name': 'FINDNAME', 'email': 'sd.linjeforening@gmail.com'},
            {'name': 'FINDNAME', 'email': 'socius.extremus@hotmail.no'},

            # {'subscriber': 'mail', 'name': 'Karrieredagen Dragvoll', 'email': 'post@karrieredagendragvoll.no'},
            # {'subscriber': 'mail', 'name': 'Det Historiske Selskab', 'email': 'ntnu_dhs@hotmail.com'},
            # {'subscriber': 'mail', 'name': 'CAF', 'email': 'idrett@hotmail.com'},
            # {'subscriber': 'mail', 'name': 'ELF', 'email': 'ntnuelf@gmail.com'},
            # {'subscriber': 'mail', 'name': 'PSI', 'email': 'psi.linjeforening@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Katharsis', 'email': 'linjeforeningenkatharsis@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Geolf', 'email': 'info.geolf@gmail.com'},
            # {'subscriber': 'mail', 'name': 'De Passe Simple', 'email': 'depassesimple@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Eureka', 'email': 'eurekalinjeforening@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Sturm Und Drang', 'email': 'sturmunddrang.ntnu@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Theodor', 'email': 'theodor.arkeologi@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Kwakiutl', 'email': 'sosant.ntnu@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Primetime', 'email': 'primetime.ntnu@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Akwaaba', 'email': 'akwaabapost.ntnu@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Jump Cut', 'email': 'jumpcut.dragvoll@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Panoptikon', 'email': 'tverrfagligkult@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Kultura', 'email': 'kulturalinjeforening@gmail.com'},
            # {'subscriber': '', 'name': 'Teaterlosjen', 'email': 'teaterlosjen@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Pareto', 'email': 'pareto.linjeforening@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Dionysos', 'email': 'dionysoslinjeforening@gmail.com'},
            # {'subscriber': 'mail', 'name': 'De Folkevalgte', 'email': 'defolkevalgte@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Apeiron', 'email': 'apeiron.ntnu@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Psykolosjen', 'email': 'psykolosjen@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Paideia', 'email': 'paideia@live.no'},
            # {'subscriber': 'mail', 'name': 'Socius Extremus', 'email': 'socius.extremus@hotmail.no'},
            # {'subscriber': 'mail', 'name': 'Erudio', 'email': 'erudiostyret@hotmail.com'},
            # {'subscriber': 'mail', 'name': 'Studentrådet SVT', 'email': 'svt@studentrad.no'},
            # {'subscriber': 'mail', 'name': 'LiMP', 'email': 'linjeforeningen.limp@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Ivrig', 'email': 'ivrig.linjeforening@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Studentrådet HF', 'email': 'hf@studentrad.no'},
            # {'subscriber': 'mail', 'name': 'Ludimus', 'email': 'ludimus@list.stud.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Gengangere', 'email': 'gengangere@list.stud.ntnu.no'}
        ]},
        {'name': 'gloshaugen', 'members': [
            {'name': 'FINDNAME', 'email': 'aarhonen-hs@list.stud.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'abakus@abakus.no'},
            {'name': 'FINDNAME', 'email': 'delta@delta.org.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'hs@omega.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'ilpresidente.leonardo@gmail.com'},
            {'name': 'FINDNAME', 'email': 'linjeforeningjanus@gmail.com'},
            {'name': 'FINDNAME', 'email': 'nabla@nabla.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'online@online.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'placebo@list.stud.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'post@broderskabet.no'},
            {'name': 'FINDNAME', 'email': 'signifikant-styret@org.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'solan-leder@entreprenorskolen.no'},
            {'name': 'FINDNAME', 'email': 'styret@bergstud.no'},
            {'name': 'FINDNAME', 'email': 'styret@emilweb.no'},
            {'name': 'FINDNAME', 'email': 'styret@hc.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'styret@hybrida.no'},
            {'name': 'FINDNAME', 'email': 'styret@mannhullet.no'},
            {'name': 'FINDNAME', 'email': 'styret@smorekoppen.no'},
            {'name': 'FINDNAME', 'email': 'styret@spanskroret.no'},
            {'name': 'FINDNAME', 'email': 'styret@timini.no'},
            {'name': 'FINDNAME', 'email': 'styret@volvox.no'},

            # {'subscriber': 'mail', 'name': 'Hybrida', 'email': 'styret@hybrida.no'},
            # {'subscriber': 'mail', 'name': 'Volvox', 'email': 'volvox-styre@list.stud.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Delta', 'email': 'delta@list.stud.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Alf', 'email': 'alf-styret@list.stud.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Mannhullet', 'email': 'styret@mannhullet.no'},
            # {'subscriber': 'mail', 'name': 'Spanskrøret', 'email': 'styre@spanskroret.no'},
            # {'subscriber': 'mail', 'name': 'Aarhønen', 'email': 'hs@aarhonen.no'},
            # {'subscriber': 'mail', 'name': 'Timini', 'email': 'styret@timini.no'},
            # {'subscriber': 'mail', 'name': 'Smørekoppen', 'email': 'styret@smorekoppen.no'},
            # {'subscriber': 'mail', 'name': 'Online', 'email': 'online@online.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Nabla', 'email': 'nabla@nabla.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'HC', 'email': 'styret@hc.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Janus', 'email': 'janus@org.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Bergstuderendes Forening', 'email': 'bsf@org.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Emil', 'email': 'styret@emilweb.no'},
            # {'subscriber': 'mail', 'name': 'Leonardo', 'email': 'leonardo-styret@list.stud.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Omega', 'email': 'omega@omega.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Placebo', 'email': 'placebo@list.stud.ntnu.no'},
            # {'subscriber': '', 'name': 'Solan', 'email': 'solan@entreprenorskolen.no'},
            # {'subscriber': 'mail', 'name': 'Abakus', 'email': 'abakus@abakus.no'}
        ]},
        {'name': 'kalvskinnet', 'members': [
            {'name': 'FINDNAME', 'email': 'hs@tihlde.org'},
            {'name': 'FINDNAME', 'email': 'leder@elektra.io'},
            {'name': 'FINDNAME', 'email': 'leder@mit.teknikersamfunn.no'},
            {'name': 'FINDNAME', 'email': 'leder@vivas.teknikersamfunn.no'},
            {'name': 'FINDNAME', 'email': 'nutrixlinjeforening@gmail.com'},
            {'name': 'FINDNAME', 'email': 'postmottak@studentalt.no'},
            {'name': 'FINDNAME', 'email': 'styret@bygging.no'},
            {'name': 'FINDNAME', 'email': 'styret@logitas.no'},
        ]},
        {'name': 'kjellere', 'members': [
            {'name': 'FINDNAME', 'email': 'aarhonen-krosjef@list.stud.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'dragvollkjelleren@gmail.com'},
            {'name': 'FINDNAME', 'email': 'emilkjelleren@gmail.com'},
            {'name': 'FINDNAME', 'email': 'icot09@gmail.com'},
            {'name': 'FINDNAME', 'email': 'kielder@omega.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'kjeller@bergstud.no'},
            {'name': 'FINDNAME', 'email': 'kjeller@januslinjeforening.no'},
            {'name': 'FINDNAME', 'email': 'kjelleren@ntnui.no'},
            {'name': 'FINDNAME', 'email': 'kjellersjef@abakus.no'},
            {'name': 'FINDNAME', 'email': 'kjellersjef@dykkergruppa.no'},
            {'name': 'FINDNAME', 'email': 'kjellersjef@hybrida.no'},
            {'name': 'FINDNAME', 'email': 'kjellersjef@mannhullet.no'},
            {'name': 'FINDNAME', 'email': 'kjellersjef@nabla.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'kjellersjef@smorekoppen.no'},
            {'name': 'FINDNAME', 'email': 'kjellerstyret@hc.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'lauget-barsjef@list.stud.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'psykolosjen@gmail.com'},
            {'name': 'FINDNAME', 'email': 'realfagskjellern-kjellersjef@list.stud.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'sykkel-kjeller@org.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'taktlaus-kjeller@list.stud.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'trondheim@isu-norway.no'},
            {'name': 'FINDNAME', 'email': 'vorsvarsminister@timini.no'},

            # {'subscriber': '', 'name': 'Smørekoppen', 'email': 'kjellersjef@smorekoppen.no'},
            # {
            #     'subscriber': '',
            #     'name': 'Bergstuderendes Forening Kjellersjef',
            #     'email': 'bsf-kjellersjef@org.ntnu.no'
            # },
            # {'subscriber': '', 'name': 'Hybrida', 'email': 'hybrida-kjeller@org.ntnu.no'},
            # {'subscriber': '', 'name': 'Dragvoll Kjelleren', 'email': 'dragvollkjelleren@gmail.com'},
            # {'subscriber': '', 'name': 'ICOT', 'email': 'icot09@gmail.com'},
            # {'subscriber': '', 'name': 'Emil Kjellern', 'email': 'emilkjelleren@gmail.com'},
            # {'subscriber': '', 'name': 'Lauget', 'email': 'lauget-barsjef@list.stud.ntnu.no'},
            # {'subscriber': '', 'name': 'De Taktlause', 'email': 'taktlaus-kjeller@list.stud.ntnu.no'},
            # {'subscriber': '', 'name': 'HC', 'email': 'kjellerstyret@hc.ntnu.no'},
            # {'subscriber': '', 'name': 'Timini', 'email': 'kjellersjef@timini.no'},
            # {'subscriber': '', 'name': 'Dykkergruppa', 'email': 'kjellersjef@dykkergruppa.no'},
            # {'subscriber': '', 'name': 'Nabla', 'email': 'kjellersjef@nabla.ntnu.no'},
            # {'subscriber': '', 'name': 'LaBamba', 'email': 'kjellersjef@abakus.no'},
            # {'subscriber': '', 'name': 'Omega', 'email': 'kielder@omega.ntnu.no'},
            # {'subscriber': '', 'name': 'Mannhullet', 'email': 'kjellersjef@mannhullet.no'},
            # {'subscriber': '', 'name': 'Janus Kjellersjef', 'email': 'janus-kjellersjef@org.ntnu.no'},
            # {
            #     'subscriber': '',
            #     'name': 'Realfagskjellern',
            #     'email': 'realfagskjellern-kjellersjef@list.stud.ntnu.no'
            # },
            # {'subscriber': '', 'name': 'isu-orga', 'email': 'isu-orga@list.stud.ntnu.no'},
            # {'subscriber': '', 'name': 'Aarhønen', 'email': 'aarhonen-krosjef@list.stud.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'NTNUI', 'email': 'solveig.blandkjenn@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Psykolosjen', 'email': 'psykolosjen@gmail.com'}
        ]},
        {'name': 'foreninger', 'members': [
            {'name': 'Linjeforeninger', 'email': 'linjeforeninger@online.ntnu.no'},
            {'name': 'Masterforeninger', 'email': 'masterforeninger@online.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'badcom.mail@gmail.com'},
            {'name': 'FINDNAME', 'email': 'hovedstyret@ntnui.no'},
            {'name': 'FINDNAME', 'email': 'ntnu@radiorevolt.no'},
            {'name': 'FINDNAME', 'email': 'sti@studenttinget.no'},
            {'name': 'FINDNAME', 'email': 'styret@samfundet.no'},
            {'name': 'FINDNAME', 'email': 'styret@stv.no'},
            {'name': 'FINDNAME', 'email': 'vt@velferdstinget.no'},

            # {'subscriber': '', 'name': 'NTNUI', 'email': 'hovedstyret@ntnui.no'},
            # {'subscriber': '', 'name': 'Radio Revolt', 'email': 'post@radiorevolt.no'},
            # {'subscriber': '', 'name': 'Styret i Samfundet', 'email': 'styret@samfundet.no'},
            # {'subscriber': '', 'name': 'Student-TV', 'email': 'styret@stv.no'},
            # {'subscriber': '', 'name': 'Under Dusken', 'email': 'styret@underdusken.no'},
            # {'subscriber': '', 'name': 'Velferdstinget', 'email': 'vt@velferdstinget.no'},
            # {'subscriber': 'mail', 'name': 'Linjeforeninger på NTN', 'email': 'linjeforeninger@online.ntnu.no'},
            # {
            #     'subscriber': 'mail',
            #     'name': 'Masterforeninger på Gløshaugen',
            #     'email': 'masterforeninger@online.ntnu.no'
            # },
            # {'subscriber': 'mail', 'name': 'Studenttinget', 'email': 'sti@studenttinget.no'}
        ]},
        {'name': 'masterforeninger', 'members': [
            {'name': 'FINDNAME', 'email': 'kontakt@projeksjon.no'},
            {'name': 'FINDNAME', 'email': 'post@hippodamus.no'},
            {'name': 'FINDNAME', 'email': 'solan-leder@entreprenorskolen.no'},
            {'name': 'FINDNAME', 'email': 'soma@list.stud.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'symbiosis.board@gmail.com'},

            # {'subscriber': 'mail', 'name': 'Soma', 'email': 'soma@list.stud.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Projeksjon', 'email': 'kontakt@projeksjon.no'},
            # {'subscriber': 'mail', 'name': 'Symbiosis', 'email': 'symbiosis.board@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Signifikant', 'email': 'signifikant-styret@org.ntnu.no'},
            # {'subscriber': '', 'name': 'Solan', 'email': 'solan@entreprenorskolen.no'},
            # {'subscriber': 'mail', 'name': 'Hippodamus', 'email': 'post@hippodamus.no'}
        ]},
        {'name': 'sr-samarbeid', 'members': [
            {'name': 'FINDNAME', 'email': 'delta@list.stud.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'hs@abakus.no'},
            {'name': 'FINDNAME', 'email': 'hs@omega.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'nabla@nabla.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'studentrad_ime-medlem@org.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'styre@spanskroret.no'},
            {'name': 'FINDNAME', 'email': 'styret@elektra.io'},
            {'name': 'FINDNAME', 'email': 'styret@emilweb.no'},

            # {'subscriber': '', 'name': 'Studentrådet IME', 'email': 'studentrad_ime-medlem@org.ntnu.no'},
            # {'subscriber': '', 'name': 'Spanskrøret', 'email': 'styre@spanskroret.no'},
            # {'subscriber': 'mail', 'name': 'Delta', 'email': 'delta@list.stud.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Online', 'email': 'hovedstyret@online.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Abakus', 'email': 'hs@abakus.no'},
            # {'subscriber': 'mail', 'name': 'Omega', 'email': 'hs@omega.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Nabla', 'email': 'nabla@nabla.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Emil', 'email': 'styret@emilweb.no'}
        ]},
        {'name': 'iv-samarbeid', 'members': [
            {'name': 'FINDNAME', 'email': 'hs@aarhonen.no'},
            {'name': 'FINDNAME', 'email': 'hybrida@org.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'medlem@sr-iv.no'},
            {'name': 'FINDNAME', 'email': 'post@teknologiporten.no'},
            {'name': 'FINDNAME', 'email': 'smore-styret@list.stud.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'styret@bergstud.no'},
            {'name': 'FINDNAME', 'email': 'styret@emilweb.no'},
            {'name': 'FINDNAME', 'email': 'styret@mannhullet.no'},

            # {'subscriber': 'mail', 'name': 'Mannhullet', 'email': 'styret@mannhullet.no'},
            # {'subscriber': 'mail', 'name': 'Aarhønen', 'email': 'hs@aarhonen.no'},
            # {'subscriber': 'mail', 'name': 'Studentrådet IVT', 'email': 'ivt@studentradet.no'},
            # {'subscriber': 'mail', 'name': 'Hybrida', 'email': 'hybrida@org.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Smørekoppen', 'email': 'smore-styret@list.stud.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'BSF', 'email': 'bsf@org.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Teknologiporten', 'email': 'post@teknologiporten.no'},
            # {'subscriber': 'mail', 'name': 'Leonardo', 'email': 'leonardo-hs@list.stud.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Emil', 'email': 'styret@emilweb.no'}
        ]},
        {'name': 'linjeledere', 'members': [
            {'name': 'FINDNAME', 'email': 'aarhonen-kanzler@list.stud.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'buckminister@timini.no'},
            {'name': 'FINDNAME', 'email': 'delta.leder@gmail.com'},
            {'name': 'FINDNAME', 'email': 'dominus@broderskabet.no'},
            {'name': 'FINDNAME', 'email': 'formann@mannhullet.no'},
            {'name': 'FINDNAME', 'email': 'ilpresidente.leonardo@gmail.com'},
            {'name': 'FINDNAME', 'email': 'janus-president@org.ntnu.no'},
            #{'name': 'FINDNAME', 'email': 'leder-deprecated@abakus.no'},
            {'name': 'FINDNAME', 'email': 'leder@bergstud.no'},
            {'name': 'FINDNAME', 'email': 'leder@emilweb.no'},
            {'name': 'FINDNAME', 'email': 'leder@hybrida.no'},
            {'name': 'FINDNAME', 'email': 'leder@nabla.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'leder@online.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'leder@volvox.no'},
            {'name': 'FINDNAME', 'email': 'phormand@hc.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'phormand@smorekoppen.no'},
            {'name': 'FINDNAME', 'email': 'placebo-leder@org.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'rektor@spanskroret.no'},
            {'name': 'FINDNAME', 'email': 'solan-leder@entreprenorskolen.no'},
            {'name': 'FINDNAME', 'email': 'sti@studenttinget.no'},
            {'name': 'FINDNAME', 'email': 'stormeister@omega.ntnu.no'},
            {'name': 'FINDNAME', 'email': 'styrerep@studenttinget.no'},
            {'name': 'FINDNAME', 'email': 'bakbenken@online.ntnu.no'},

            # {'subscriber': 'mail', 'name': 'Timini', 'email': 'buckminister@timini.no'},
            # {'subscriber': 'mail', 'name': 'Nabla', 'email': 'leder@nabla.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Placebo', 'email': 'placebo-leder@org.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Omega', 'email': 'stormeister@omega.ntnu.no'},
            # {'subscriber': '', 'name': 'Smørekoppen', 'email': 'phormand@smorekoppen.no'},
            # {'subscriber': 'mail', 'name': 'Hybrida', 'email': 'leder@hybrida.no'},
            # {'subscriber': '', 'name': 'Janus', 'email': 'janus-president@list.stud.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Leonardo', 'email': 'leonardo-leder@list.stud.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Solan', 'email': 'solan-leder@entreprenorskolen.no'},
            # {'subscriber': '', 'name': 'Tidligere Linjeledere', 'email': 'bakbenken@online.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Spanskrøret', 'email': 'rektor@spanskroret.no'},
            # {'subscriber': 'mail', 'name': 'Mannhullet', 'email': 'formann@mannhullet.no'},
            # {'subscriber': 'mail', 'name': 'Abakus', 'email': 'leder@abakus.no'},
            # {'subscriber': 'mail', 'name': 'Emil', 'email': 'leder@emilweb.no'},
            # {'subscriber': 'mail', 'name': 'Online', 'email': 'leder@online.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Volvox', 'email': 'volvox-leder@list.stud.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Aarhønen', 'email': 'aarhonen-kanzler@list.stud.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Berg', 'email': 'bsf-leder@list.stud.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'Delta', 'email': 'delta.leder@gmail.com'},
            # {'subscriber': 'mail', 'name': 'Alf', 'email': 'alf-leder@list.stud.ntnu.no'},
            # {'subscriber': 'mail', 'name': 'HC', 'email': 'phormand@hc.ntnu.no'}
        ]}
    ]

    return render(request, 'mailinglists/index.html', {'lists': lists})
