# -*- coding: utf-8 -*-

from django.shortcuts import render


def index(request):
    lists = [
        {
            "name": "linjeforeninger",
            "members": [
                {"name": "Dragvoll", "email": "dragvoll@online.ntnu.no"},
                {"name": "Gløshaugen", "email": "gloshaugen@online.ntnu.no"},
                {"name": "Kalvskinnet", "email": "kalvskinnet@online.ntnu.no"},
            ],
        },
        {
            "name": "dragvoll",
            "members": [
                {"name": "Akwaaba", "email": "akwaabapost.ntnu@gmail.com"},
                {"name": "Apeiron", "email": "apeiron.ntnu@gmail.com"},
                {"name": "CAF", "email": "cafidrett@gmail.com"},
                {"name": "Communitas", "email": "sosant.ntnu@gmail.com"},
                {"name": "De Folkevalgte", "email": "defolkevalgte@gmail.com"},
                {"name": "De Passe Simple", "email": "depassesimple@gmail.com"},
                {"name": "Dionysos", "email": "dionysoslinjeforening@gmail.com"},
                {"name": "Det Gyldne Snitt", "email": "post.detgyldnesnitt@gmail.com"},
                {"name": "Det Historiske Selskab", "email": "ntnu_dhs@hotmail.com"},
                {"name": "Erudio", "email": "styret@erudiontnu.no"},
                {"name": "Eureka", "email": "eurekalinjeforening@gmail.com"},
                {"name": "Fauréningen", "email": "faureningen@gmail.com"},
                {"name": "Gengangere", "email": "gengangerentnu@gmail.com"},
                {"name": "HF Studentrådet", "email": "hf@studentrad.no"},
                {"name": "Geolf", "email": "info.geolf@gmail.com"},
                {"name": "IVRig", "email": "ivrig.linjeforening@gmail.com"},
                {"name": "Jump Cut", "email": "jumpcut.dragvoll@gmail.com"},
                {"name": "Kultura", "email": "kulturalinjeforening@gmail.com"},
                {"name": "Leviathan", "email": "leviathan.ntnu@gmail.com"},
                {"name": "LiMP", "email": "linjeforeningenlimp@gmail.com"},
                {"name": "Lipton", "email": "liptonlinjeforening@gmail.com"},
                {"name": "Los Elegidos", "email": "loselegidoslinjeforening@gmail.com"},
                {"name": "Paideia", "email": "paideiantnu@gmail.com"},
                {"name": "Pareto", "email": "pareto.linjeforening@gmail.com"},
                {"name": "Primetime", "email": "primetime.ntnu@gmail.com"},
                {"name": "Psi", "email": "psi.linjeforening@gmail.com"},
                {"name": "Psykolosjen", "email": "psykolosjen@gmail.com"},
                {"name": "Socius Extremus", "email": "socius.extremus@hotmail.no"},
                {"name": "Sturm und Drang", "email": "sd.linjeforening@gmail.com"},
                {"name": "SU Studentrådet", "email": "su@studentrad.no"},
                {"name": "Teaterlosjen", "email": "hs@teaterlosjen.no"},
                {"name": "Theodor", "email": "theodor.arkeologi@gmail.com"},
                {"name": "YFF", "email": "yff.ntnu@hotmail.com"},
            ],
        },
        {
            "name": "gloshaugen",
            "members": [
                {"name": "Abakus", "email": "abakus@abakus.no"},
                {"name": "A/F Smørekoppen", "email": "styret@smorekoppen.no"},
                {
                    "name": "Arkitektstudentenes Broderskab",
                    "email": "kontakt@broderskabet.no",
                },
                {"name": "Bergstuderendes Forening", "email": "styret@bergstud.no"},
                {"name": "Delta", "email": "delta@delta.org.ntnu.no"},
                {"name": "Elektra", "email": "leder@elektra.io"},
                {"name": "Emil", "email": "styret@emilweb.no"},
                {"name": "HC", "email": "styret@hc.ntnu.no"},
                {"name": "H.M. Aarhønen", "email": "aarhonen-hs@list.stud.ntnu.no"},
                {"name": "Hybrida", "email": "styret@hybrida.no"},
                {"name": "Janus", "email": "janus@janus.org.ntnu.no"},
                {"name": "Leonardo", "email": "ilpresidente.leonardo@gmail.com"},
                {"name": "Mannhullet", "email": "styret@mannhullet.no"},
                {
                    "name": "MiT (ligger også på Kalvskinnet)",
                    "email": "leder@maskining.no",
                },
                {"name": "Nabla", "email": "nabla@nabla.ntnu.no"},
                {"name": "Nucleus", "email": "nucleuslinjeforening@gmail.com"},
                {"name": "Omega", "email": "hs@omega.ntnu.no"},
                {"name": "Online", "email": "online@online.ntnu.no"},
                {"name": "Placebo", "email": "placebo@list.stud.ntnu.no"},
                {"name": "Signifikant", "email": "signifikant-styret@org.ntnu.no"},
                {"name": "Solan", "email": "solan-leder@entreprenorskolen.no"},
                {"name": "Spanskrøret", "email": "styret@spanskroret.no"},
                {"name": "STØH", "email": "leder.stoh@gmail.com"},
                {"name": "TIHLDE", "email": "hs@tihlde.org"},
                {"name": "Timini", "email": "styret@timini.no"},
                {"name": "Vivas", "email": "leder@vivas.teknikersamfunn.no"},
                {"name": "Volvox & Alkymisten", "email": "styret@volvox.no"},
            ],
        },
        {
            "name": "kalvskinnet",
            "members": [
                {"name": "KOM", "email": "kom.linjeforening@gmail.com"},
                {"name": "Logitas", "email": "styret@logitas.no"},
                {
                    "name": "MiT (ligger også på Gløshaugen)",
                    "email": "leder@maskining.no",
                },
                {"name": "Nutrix", "email": "nutrixlinjeforening@gmail.com"},
                {"name": "SALT", "email": "postmottak@studentalt.no"},
                {"name": "Tim & Shænko", "email": "styret@bygging.no"},
            ],
        },
        {
            "name": "kjellere",
            "members": [
                {"name": "Dragvollkjelleren", "email": "dragvollkjelleren@gmail.com"},
                {
                    "name": "Emil, Smørekoppen",
                    "email": "emil.smorekoppenkjelleren@gmail.com",
                },
                {"name": "Hybrida, Berg, Timini", "email": "kjellerkom@hybrida.no"},
                {"name": "Nabla, Janus, HC", "email": "kjellern.hk18@nabla.ntnu.no"},
                {
                    "name": "Dykkergruppa, NTNUI",
                    "email": "styret@dypet.dykkergruppa.no",
                },
                {"name": "Labamba", "email": "labamba@abakus.no"},
                {
                    "name": "Omega, Psykolosjen",
                    "email": "kjellersjefkielderen@gmail.com",
                },
                {
                    "name": "Realfagskjelleren",
                    "email": "realfagskjellern-styre@list.stud.ntnu.no",
                },
                {"name": "H.M. Aarhønen", "email": "krosjef@aarhonen.org.ntnu.no"},
            ],
        },
        {
            "name": "foreninger",
            "members": [
                {"name": "Linjeforeninger", "email": "linjeforeninger@online.ntnu.no"},
                {
                    "name": "Masterforeninger",
                    "email": "masterforeninger@online.ntnu.no",
                },
                {"name": "Badcom", "email": "badcom.mail@gmail.com"},
                {"name": "NTNUI", "email": "hovedstyret@ntnui.no"},
                {"name": "Radio Revolt", "email": "ntnu@radiorevolt.no"},
                {"name": "Revolve NTNU", "email": "post@revolve.no"},
                {"name": "Studenttinget", "email": "sti@studenttinget.no"},
                {"name": "Samfundet", "email": "styret@samfundet.no"},
                {"name": "Student-TV", "email": "styret@stv.no"},
                {"name": "Sukkerhuset", "email": "styret@sukkerhuset.no"},
                {"name": "Velferdstinget", "email": "vt@velferdstinget.no"},
                {"name": "Teknologiporten", "email": "post@teknologiporten.no"},
            ],
        },
        {
            "name": "masterforeninger",
            "members": [
                {"name": "Hippodamus", "email": "post@hippodamus.no"},
                {"name": "Projeksjon", "email": "kontakt@projeksjon.no"},
                {"name": "ProMan", "email": "promanntnu@gmail.com"},
                {"name": "Solan", "email": "solan-leder@entreprenorskolen.no"},
                {"name": "Soma", "email": "soma@list.stud.ntnu.no"},
                {"name": "Symbiosis", "email": "symbiosis.board@gmail.com"},
            ],
        },
        {
            "name": "sr-samarbeid",
            "members": [
                {"name": "Delta", "email": "delta@delta.org.ntnu.no"},
                {"name": "Abakus", "email": "hs@abakus.no"},
                {"name": "Omega", "email": "hs@omega.ntnu.no"},
                {"name": "Online", "email": "hovedstyret@online.ntnu.no"},
                {"name": "Nabla", "email": "nabla@nabla.ntnu.no"},
                {
                    "name": "Studentrådet IME",
                    "email": "studentrad_ime-medlem@org.ntnu.no",
                },
                {"name": "Spanskrøret", "email": "styre@spanskroret.no"},
                {"name": "Elektra", "email": "styret@elektra.io"},
                {"name": "Emil", "email": "styret@emilweb.no"},
                {"name": "Epsilon", "email": "epsilon.linjeforening@gmail.com"},
                {"name": "TIHLDE", "email": "hs@tihlde.org"},
                {"name": "INGa", "email": "inga@hig.no"},
                {"name": "Login", "email": "login@gjovik.ntnu.no"},
            ],
        },
        {
            "name": "iv-samarbeid",
            "members": [
                {"name": "H.M. Aarhønen", "email": "hs@aarhonen.no"},
                {"name": "Hybrida", "email": "hybrida@org.ntnu.no"},
                {"name": "Studentrådet IV", "email": "medlem@sr-iv.no"},
                {"name": "Teknologiporten", "email": "post@teknologiporten.no"},
                {"name": "A/F Smørekoppen", "email": "styret@smorekoppen.no"},
                {"name": "Bergstuderendes Forening", "email": "styret@bergstud.no"},
                {"name": "Emil", "email": "styret@emilweb.no"},
                {"name": "Mannhullet", "email": "styret@mannhullet.no"},
            ],
        },
        {
            "name": "linjeledere",
            "members": [
                {
                    "name": "H.M. Aarhønen",
                    "email": "aarhonen-kanzler@list.stud.ntnu.no",
                },
                {"name": "Timini", "email": "buckminister@timini.no"},
                {"name": "Delta", "email": "delta.leder@gmail.com"},
                {
                    "name": "Arkitektstudentenes Broderskab",
                    "email": "dominus@broderskabet.no",
                },
                {"name": "Mannhullet", "email": "formann@mannhullet.no"},
                {"name": "Leonardo", "email": "ilpresidente.leonardo@gmail.com"},
                {"name": "Janus", "email": "janus-president@org.ntnu.no"},
                {"name": "Abakus", "email": "leder@abakus.no"},
                {"name": "Bergstuderendes Forening", "email": "leder@bergstud.no"},
                {"name": "Emil", "email": "leder@emilweb.no"},
                {"name": "Hybrida", "email": "leder@hybrida.no"},
                {"name": "Nabla", "email": "leder@nabla.ntnu.no"},
                {"name": "Online", "email": "leder@online.ntnu.no"},
                {"name": "Volvox & Alkymisten", "email": "leder@volvox.no"},
                {"name": "HC", "email": "phormand@hc.ntnu.no"},
                {"name": "A/F Smørekoppen", "email": "phormand@smorekoppen.no"},
                {"name": "Placebo", "email": "placebo-leder@org.ntnu.no"},
                {"name": "Spanskrøret", "email": "rektor@spanskroret.no"},
                {"name": "Solan", "email": "solan-leder@entreprenorskolen.no"},
                {"name": "Studenttinget", "email": "sti@studenttinget.no"},
                {"name": "Omega", "email": "stormeister@omega.ntnu.no"},
                {"name": "Studenttinget", "email": "styrerep@studenttinget.no"},
                {"name": "Bakbenken", "email": "bakbenken@online.ntnu.no"},
                {"name": "Tim & Shænko", "email": "leder@bygging.no"},
            ],
        },
        {
            "name": "glosfaddere",
            "members": [
                {"name": "H.M. Aarhønen", "email": "aarhonen-skogvokter@list.ntnu.no"},
                {"name": "Timini", "email": "ansvarsminister@timini.no"},
                {
                    "name": "Bergstuderendes Forening",
                    "email": "bsf-fadderkom@org.ntnu.no",
                },
                {"name": "Emil", "epost": "fadderansvarlig@emilweb.no"},
                {"name": "HC", "epost": "fadderkom@hc.ntnu.no"},
                {"name": "Hybrida", "epost": "faddersjef@hybrida.no"},
                {"name": "Omega", "epost": "faddersjef@omega.ntnu.no"},
                {"name": "Spansrøret", "epost": "faddersjef@spanskroret.no"},
                {"name": "Janus", "epost": "janus-president@org.ntnu.no"},
                {"name": "Leonardo", "epost": "leonardo-forstemann@list.stud.ntnu.no"},
                {"name": "A/F Smørekoppen", "epost": "phaddercom@smorekoppen.no"},
                {"name": "Placebo", "epost": "placebo-faddersjef@list.stud.ntnu.no"},
                {"name": "Nabla", "epost": "sekretaer@nabla.ntnu.no"},
                {"name": "Online", "epost": "velkom@online.ntnu.no"},
                {"name": "Volvox & Alkymisten", "epost": "volvox-fadder@list.ntnu.no"},
            ],
        },
    ]

    return render(request, "mailinglists/index.html", {"lists": lists})
