# Generated by Django 5.0.4 on 2024-04-07 11:17

import uuid
from datetime import timedelta

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from apps.payment import status


def m23_forward(apps, schema_editor):
    Payment = apps.get_model("payment", "Payment")

    # Payment type 3 is 'Utsettelse'
    for payment in Payment.objects.filter(payment_type=3):
        payment.delay_duration = timedelta(days=payment.delay)
        payment.save()


def m23_backward(apps, schema_editor):
    Payment = apps.get_model("payment", "Payment")

    # Payment type 3 is 'Utsettelse'
    for payment in Payment.objects.filter(payment_type=3):
        payment.delay = payment.delay_duration.days
        payment.save()


def m29_forward(apps, schema_editor):
    PaymentRelation = apps.get_model("payment", "PaymentRelation")

    success_relations = PaymentRelation.objects.filter(status=status.SUCCEEDED)
    for relation in success_relations:
        relation.status = status.DONE
        relation.save(update_fields=["status"])

    refunded_relations = PaymentRelation.objects.filter(status=status.REFUNDED)
    for relation in refunded_relations:
        relation.status = status.REMOVED
        relation.save(update_fields=["status"])


class Migration(migrations.Migration):
    replaces = [
        ("payment", "0001_initial"),
        ("payment", "0002_payment_active"),
        ("payment", "0003_auto_20150328_1600"),
        ("payment", "0004_auto_20150415_2210"),
        ("payment", "0005_auto_20150429_1758"),
        ("payment", "0006_auto_20151014_1938"),
        ("payment", "0007_paymenttransaction"),
        ("payment", "0008_auto_20151017_2047"),
        ("payment", "0009_auto_20151021_2150"),
        ("payment", "0010_paymenttransaction_used_stripe"),
        ("payment", "0007_auto_20151029_1558"),
        ("payment", "0011_merge"),
        ("payment", "0012_auto_20160128_1719"),
        ("payment", "0013_auto_20160210_2010"),
        ("payment", "0014_auto_20160309_2133"),
        ("payment", "0015_auto_20160427_2117"),
        ("payment", "0016_auto_20160427_2253"),
        ("payment", "0017_auto_20160428_1116"),
        ("payment", "0015_auto_20160429_1542"),
        ("payment", "0016_auto_20160901_2213"),
        ("payment", "0018_merge"),
        ("payment", "0019_paymenttransaction_unique_id"),
        ("payment", "0020_auto_20180221_1916"),
        ("payment", "0021_auto_20180312_1713"),
        ("payment", "0022_payment_delay_duration"),
        ("payment", "0023_auto_20180424_1432"),
        ("payment", "0024_auto_20180424_1450"),
        ("payment", "0025_auto_20180424_1451"),
        ("payment", "0026_auto_20190506_1719"),
        ("payment", "0027_auto_20190515_1412"),
        ("payment", "0028_set_succeeded_transactions_to_done"),
        ("payment", "0029_set_succeeded_relations_to_done"),
        ("payment", "0030_auto_20190916_1421"),
        ("payment", "0031_paymenttransaction_source"),
        ("payment", "0032_auto_20200305_1403"),
        ("payment", "0033_remove_paymenttransaction_used_stripe"),
        ("payment", "0034_auto_20200305_1444"),
        ("payment", "0035_auto_20200307_1530"),
        ("payment", "0036_auto_20200525_1421"),
        ("payment", "0037_alter_payment_payment_type"),
        ("payment", "0038_delete_paymenttransaction"),
    ]

    initial = True

    dependencies = [
        ("contenttypes", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "deadline",
                    models.DateTimeField(blank=True, null=True, verbose_name="frist"),
                ),
                (
                    "added_date",
                    models.DateTimeField(auto_now=True, verbose_name="opprettet dato"),
                ),
                ("changed_date", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "last_changed_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "delay",
                    models.SmallIntegerField(
                        blank=True, default=2, null=True, verbose_name="utsettelse"
                    ),
                ),
                (
                    "payment_type",
                    models.SmallIntegerField(
                        choices=[(1, "Umiddelbar"), (2, "Frist"), (3, "Utsettelse")],
                        default=1,
                        verbose_name="type",
                    ),
                ),
                (
                    "stripe_key",
                    models.CharField(
                        choices=[
                            ("arrkom", "arrkom"),
                            ("prokom", "prokom"),
                            ("trikom", "trikom"),
                            ("fagkom", "fagkom"),
                        ],
                        default="arrkom",
                        max_length=10,
                        verbose_name="stripe key",
                    ),
                ),
                (
                    "delay_duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="utsettelse"
                    ),
                ),
            ],
            options={
                "verbose_name": "betaling",
                "verbose_name_plural": "betalinger",
                "unique_together": {("content_type", "object_id")},
            },
        ),
        migrations.CreateModel(
            name="PaymentPrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="pris")),
                (
                    "description",
                    models.CharField(max_length=128),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "pris",
                "verbose_name_plural": "priser",
            },
        ),
        migrations.CreateModel(
            name="PaymentRelation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now=True)),
                ("unique_id", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.payment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.paymentprice",
                    ),
                ),
                ("refunded", models.BooleanField(default=False)),
                ("stripe_id", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name": "betalingsrelasjon",
                "verbose_name_plural": "betalingsrelasjoner",
            },
        ),
        migrations.CreateModel(
            name="PaymentDelay",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_to", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.payment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "betalingsutsettelse",
                "verbose_name_plural": "betalingsutsettelser",
                "unique_together": {("payment", "user")},
            },
        ),
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_id", models.UUIDField(default=uuid.uuid4)),
                ("object_id", models.PositiveIntegerField(null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            code=m23_forward,
            reverse_code=m23_backward,
        ),
        migrations.RemoveField(
            model_name="payment",
            name="delay",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="delay_duration",
            new_name="delay",
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "default_permissions": ("add", "change", "delete"),
                "verbose_name": "betaling",
                "verbose_name_plural": "betalinger",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentdelay",
            options={
                "default_permissions": ("add", "change", "delete"),
                "verbose_name": "betalingsutsettelse",
                "verbose_name_plural": "betalingsutsettelser",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentprice",
            options={
                "default_permissions": ("add", "change", "delete"),
                "verbose_name": "pris",
                "verbose_name_plural": "priser",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentreceipt",
            options={"default_permissions": ("add", "change", "delete")},
        ),
        migrations.AlterModelOptions(
            name="paymentrelation",
            options={
                "default_permissions": ("add", "change", "delete"),
                "verbose_name": "betalingsrelasjon",
                "verbose_name_plural": "betalingsrelasjoner",
            },
        ),
        migrations.AlterField(
            model_name="payment",
            name="delay",
            field=models.DurationField(
                blank=True,
                help_text='Oppgi utsettelse på formatet "dager timer:min:sek"',
                null=True,
                verbose_name="utsettelse",
            ),
        ),
        migrations.AddField(
            model_name="paymentrelation",
            name="payment_intent_secret",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="paymentrelation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("succeeded", "succeeded"),
                    ("done", "done"),
                    ("refunded", "refunded"),
                    ("removed", "removed"),
                ],
                default="succeeded",
                max_length=30,
            ),
        ),
        migrations.RunPython(
            code=m29_forward,
        ),
        migrations.AlterField(
            model_name="paymentrelation",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="paymentrelation",
            name="create_receipt",
            field=models.BooleanField(
                default=True,
                help_text="Skal det sendes en kvittering for kjøpet?",
                verbose_name="Lag kvittering",
            ),
        ),
        migrations.AlterModelOptions(
            name="paymentdelay",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("active", "valid_to"),
                "verbose_name": "betalingsutsettelse",
                "verbose_name_plural": "betalingsutsettelser",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentprice",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("payment", "price"),
                "verbose_name": "pris",
                "verbose_name_plural": "priser",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentrelation",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("datetime", "unique_id"),
                "verbose_name": "betalingsrelasjon",
                "verbose_name_plural": "betalingsrelasjoner",
            },
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.SmallIntegerField(
                choices=[(1, "Immediate"), (2, "Deadline"), (3, "Delay")],
                verbose_name="type",
            ),
        ),
    ]
