# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("payment", "0015_auto_20160427_2117")]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_key",
            field=models.CharField(
                choices=[
                    ("arrkom", "arrkom"),
                    ("trikom", "trikom"),
                    ("prokom", "prokom"),
                ],
                default="arrkom",
                max_length=10,
                verbose_name="stripe key",
            ),
        )
    ]
