# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0017_auto_20160428_1116"),
        ("payment", "0016_auto_20160901_2213"),
    ]

    operations = []
