# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("payment", "0018_merge")]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="unique_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        )
    ]
