# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_paymenttransaction_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(default=None, max_length=128)),
                ('to_mail', models.EmailField(max_length=254)),
                ('from_mail', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('description', models.TextField()),
                ('transaction_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment.PaymentReceipt')),
            ],
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='unique_id',
        ),
    ]
