# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_auto_20180221_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprice',
            name='description',
            field=models.CharField(default='No description', max_length=128),
            preserve_default=False,
        ),
    ]
