# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_auto_20180312_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='delay_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='utsettelse'),
        ),
    ]
