# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 12:32
from __future__ import unicode_literals

from datetime import timedelta

from django.db import migrations
from django.db.migrations import RunPython


def forward(apps, schema_editor):
    Payment = apps.get_model("payment", "Payment")

    for payment in Payment.objects.filter(payment_type=Payment.Types.DELAY):
        payment.delay_duration = timedelta(days=payment.delay)
        payment.save()


def backward(apps, schema_editor):
    Payment = apps.get_model("payment", "Payment")

    for payment in Payment.objects.filter(payment_type=Payment.Types.DELAY):
        payment.delay = payment.delay_duration.days
        payment.save()


class Migration(migrations.Migration):

    dependencies = [("payment", "0022_payment_delay_duration")]

    operations = [RunPython(forward, backward)]
