# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("payment", "0023_auto_20180424_1432")]

    operations = [migrations.RemoveField(model_name="payment", name="delay")]
