# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_auto_20180424_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='delay_duration',
            new_name='delay',
        ),
    ]
