# Generated by Django 2.0.13 on 2019-02-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_auto_20180424_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='delay',
            field=models.DurationField(blank=True, help_text='Oppgi utsettelse på formatet "dager timer:min:sek"', null=True, verbose_name='utsettelse'),
        ),
    ]
