# Generated by Django 2.1.9 on 2019-08-22 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0029_set_succeeded_relations_to_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='FikenSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_key', models.CharField(choices=[('arrkom', 'arrkom'), ('prokom', 'prokom'), ('trikom', 'trikom'), ('fagkom', 'fagkom')], default='arrkom', max_length=20, verbose_name='Stripe key')),
                ('transaction_type', models.CharField(choices=[('kiosk', 'kiosk'), ('webshop', 'webshop'), ('event', 'event')], max_length=20, verbose_name='Transaction Type')),
                ('original_amount', models.FloatField()),
                ('kind', models.CharField(choices=[('CASH_SALE', 'CASH_SALE'), ('INVOICE', 'INVOICE'), ('EXTERNAL_INVOICE', 'EXTERNAL_INVOICE')], default='CASH_SALE', max_length=20, verbose_name='Fiken Sale kind')),
                ('paid', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
