# Generated by Django 2.1.9 on 2019-08-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0030_fikensale'),
    ]

    operations = [
        migrations.AddField(
            model_name='fikensale',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
