# Generated by Django 2.1.11 on 2019-09-29 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0030_auto_20190916_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='FikenOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('vat_type', models.CharField(choices=[('NONE', 'Ingen mva-behandling (inntekter)'), ('HIGH', 'Utgående merverdiavgift, 25 %'), ('MEDIUM', 'Utgående merverdiavgift, 15 %'), ('RAW_FISH', 'Utgående merverdiavgift, 11,11 %'), ('LOW', 'Utgående merverdiavgift, 12 %'), ('EXEMPT_IMPORT_EXPORT', 'Utførsel av varer og tjenester, 0 %'), ('EXEMPT', 'Innenlands omsetning og uttak fritatt for merverdiavgift, 0 %'), ('OUTSIDE', 'Omsetning utenfor merverdiavgiftsloven'), ('EXEMPT_REVERSE', 'Ingen mva-behandling (inntekter)')], max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Ordrelinje i Fiken',
                'verbose_name_plural': 'Ordrelinjer i Fiken',
            },
        ),
        migrations.CreateModel(
            name='FikenSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_key', models.CharField(choices=[('arrkom', 'arrkom'), ('prokom', 'prokom'), ('trikom', 'trikom'), ('fagkom', 'fagkom')], max_length=20, verbose_name='Stripe key')),
                ('transaction_type', models.CharField(choices=[('kiosk', 'kiosk'), ('webshop', 'webshop'), ('event', 'event')], max_length=20, verbose_name='Transaction Type')),
                ('original_amount', models.IntegerField()),
                ('kind', models.CharField(choices=[('CASH_SALE', 'CASH_SALE'), ('INVOICE', 'INVOICE'), ('EXTERNAL_INVOICE', 'EXTERNAL_INVOICE')], default='CASH_SALE', max_length=20, verbose_name='Fiken Sale kind')),
                ('paid', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('done', 'done'), ('refunded', 'refunded'), ('removed', 'removed')], max_length=30)),
                ('fiken_id', models.IntegerField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Salg i Fiken',
                'verbose_name_plural': 'Salg i Fiken',
            },
        ),
        migrations.CreateModel(
            name='FikenSaleAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='files/fiken/attachments')),
                ('comment', models.CharField(max_length=4000)),
                ('attach_to_sale', models.BooleanField(default=False)),
                ('attach_to_payment', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachments', to='payment.FikenSale')),
            ],
            options={
                'verbose_name': 'Bilag i Fiken',
                'verbose_name_plural': 'Bilag i Fiken',
            },
        ),
        migrations.AddField(
            model_name='fikenorderline',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='payment.FikenSale'),
        ),
    ]
