# Generated by Django 2.1.9 on 2019-08-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0031_fikensale_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fikensale',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fikensale',
            name='stripe_key',
            field=models.CharField(choices=[('arrkom', 'arrkom'), ('prokom', 'prokom'), ('trikom', 'trikom'), ('fagkom', 'fagkom')], max_length=20, verbose_name='Stripe key'),
        ),
    ]
