# Generated by Django 2.1.9 on 2019-08-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0031_auto_20190826_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='fikensale',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('done', 'done'), ('refunded', 'refunded'), ('removed', 'removed')], default='succeeded', max_length=30),
        ),
    ]
