# Generated by Django 2.1.9 on 2019-08-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0032_auto_20190823_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fikensale',
            name='original_amount',
            field=models.IntegerField(),
        ),
    ]
