# Generated by Django 2.2.10 on 2020-03-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("payment", "0032_auto_20200305_1403")]

    operations = [
        migrations.RemoveField(model_name="paymenttransaction", name="used_stripe")
    ]
