# Generated by Django 2.1.9 on 2019-08-29 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0032_fikensale_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FikenSaleAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='files/fiken/attachments')),
                ('comment', models.CharField(max_length=4000)),
                ('attach_to_sale', models.BooleanField(default=True)),
                ('attach_to_payment', models.BooleanField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='fikensale',
            name='fiken_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fikensale',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('done', 'done'), ('refunded', 'refunded'), ('removed', 'removed')], max_length=30),
        ),
        migrations.AddField(
            model_name='fikensaleattachment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachments', to='payment.FikenSale'),
        ),
    ]
