# Generated by Django 2.2.10 on 2020-03-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("payment", "0033_remove_paymenttransaction_used_stripe")]

    operations = [
        migrations.AddField(
            model_name="paymentrelation",
            name="create_receipt",
            field=models.BooleanField(
                default=True,
                help_text="Skal det sendes en kvittering for kjøpet?",
                verbose_name="Lag kvittering",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="create_receipt",
            field=models.BooleanField(
                default=True,
                help_text="Skal det sendes en kvittering for kjøpet?",
                verbose_name="Lag kvittering",
            ),
        ),
    ]
