# Generated by Django 2.2.10 on 2020-03-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("payment", "0034_auto_20200305_1444")]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True),
        )
    ]
