# Generated by Django 2.1.11 on 2019-09-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0035_auto_20190925_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fikensaleattachment',
            name='attach_to_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fikensaleattachment',
            name='attach_to_sale',
            field=models.BooleanField(default=False),
        ),
    ]
