# Generated by Django 3.0.6 on 2020-05-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0035_auto_20200307_1530"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentdelay",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("active", "valid_to"),
                "verbose_name": "betalingsutsettelse",
                "verbose_name_plural": "betalingsutsettelser",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentprice",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("payment", "price"),
                "verbose_name": "pris",
                "verbose_name_plural": "priser",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentrelation",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("datetime", "unique_id"),
                "verbose_name": "betalingsrelasjon",
                "verbose_name_plural": "betalingsrelasjoner",
            },
        ),
    ]
