# Generated by Django 3.2.23 on 2023-11-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0036_auto_20200525_1421"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.SmallIntegerField(
                choices=[(1, "Immediate"), (2, "Deadline"), (3, "Delay")],
                verbose_name="type",
            ),
        ),
    ]
