# Generated by Django 2.1.11 on 2019-09-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0036_auto_20190928_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fikenorderline',
            options={'verbose_name': 'Ordrelinje i Fiken', 'verbose_name_plural': 'Ordrelinjer i Fiken'},
        ),
        migrations.AlterModelOptions(
            name='fikensale',
            options={'verbose_name': 'Salg i Fiken', 'verbose_name_plural': 'Salg i Fiken'},
        ),
        migrations.AlterModelOptions(
            name='fikensaleattachment',
            options={'verbose_name': 'Bilag i Fiken', 'verbose_name_plural': 'Bilag i Fiken'},
        ),
    ]
