# Generated by Django 5.0.4 on 2024-04-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0037_alter_payment_payment_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentTransaction",
        ),
    ]
