# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0005_auto_20160831_1942'),
        ('approval', '0005_auto_20160906_1703'),
    ]

    operations = [
    ]
