# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('approval', '0006_auto_20170729_2222'), ('approval', '0007_auto_20170729_2319'), ('approval', '0008_auto_20170729_2325'), ('approval', '0009_auto_20170730_0029'), ('approval', '0010_auto_20170730_0055'), ('approval', '0011_auto_20170730_0104'), ('approval', '0012_auto_20170730_1405'), ('approval', '0013_auto_20170730_1416')]

    dependencies = [
        ('approval', '0005_auto_20160906_1703'),
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='opprettet')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='endret')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-postadresse')),
                ('application_text', models.TextField(verbose_name='søknadstekst')),
                ('prioritized', models.BooleanField(default=False, verbose_name='prioriter komitevalg')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='søker')),
                ('committees', models.ManyToManyField(through='approval.CommitteePriority', to='auth.Group', verbose_name='komiteer')),
                ('name', models.CharField(blank=True, max_length=69, null=True, verbose_name='navn')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'verbose_name': 'komitesøknad',
                'verbose_name_plural': 'komitesøknader',
            },
        ),
        migrations.CreateModel(
            name='CommitteePriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.SmallIntegerField(choices=[(1, '1. prioritet'), (2, '2. prioritet'), (3, '3. prioritet')], verbose_name='prioritet')),
                ('committee_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.CommitteeApplication', verbose_name='søknad')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='komite')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'verbose_name': 'komiteprioritering',
                'verbose_name_plural': 'komiteprioriteringer',
            },
        ),
    ]
