# Generated by Django 2.1 on 2019-04-03 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0007_auto_20180404_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipapproval',
            options={'permissions': (('show_membershipapproval', 'Show membership approval'),), 'verbose_name': 'medlemskapssøknad', 'verbose_name_plural': 'medlemskapssøknader'},
        ),
        migrations.AlterField(
            model_name='approval',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL, verbose_name='søker'),
        ),
    ]
