# Generated by Django 2.0.13 on 2019-02-20 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0007_auto_20180404_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL, verbose_name='søker'),
        ),
    ]
