# Generated by Django 2.2.10 on 2020-02-29 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("approval", "0008_auto_20190506_1719")]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="søker",
            ),
        ),
        migrations.AlterField(
            model_name="approval",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approved_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="godkjenner",
            ),
        ),
    ]
