# Generated by Django 3.0.4 on 2020-03-30 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("approval", "0011_auto_20200328_1032")]

    operations = [
        migrations.AlterModelOptions(
            name="committeeapplication",
            options={
                "default_permissions": ("add", "change", "delete", "view"),
                "ordering": ("created",),
                "verbose_name": "komitesøknad",
                "verbose_name_plural": "komitesøknader",
            },
        ),
        migrations.AlterModelOptions(
            name="committeepriority",
            options={
                "default_permissions": ("add", "change", "delete", "view"),
                "ordering": ("committee_application__created", "priority"),
                "verbose_name": "komiteprioritering",
                "verbose_name_plural": "komiteprioriteringer",
            },
        ),
        migrations.AlterField(
            model_name="committeepriority",
            name="committee_application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="committee_priorities",
                to="approval.CommitteeApplication",
                verbose_name="søknad",
            ),
        ),
    ]
