# Generated by Django 3.2.12 on 2022-03-21 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0014_auto_20210912_1610"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membershipapproval",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("pk",),
                "permissions": (
                    ("view_membershipapproval", "View membership approval"),
                ),
                "verbose_name": "medlemskapssøknad",
                "verbose_name_plural": "medlemskapssøknader",
            },
        ),
    ]
