# Generated by Django 5.0.4 on 2024-04-06 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0015_alter_membershipapproval_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="committeepriority",
            name="committee_application",
        ),
        migrations.RemoveField(
            model_name="committeeapplicationperiod",
            name="committees",
        ),
        migrations.RemoveField(
            model_name="committeeapplicationperiodparticipation",
            name="committeeapplicationperiod",
        ),
        migrations.RemoveField(
            model_name="committeeapplicationperiodparticipation",
            name="onlinegroup",
        ),
        migrations.RemoveField(
            model_name="committeepriority",
            name="group",
        ),
        migrations.DeleteModel(
            name="CommitteeApplication",
        ),
        migrations.DeleteModel(
            name="CommitteeApplicationPeriod",
        ),
        migrations.DeleteModel(
            name="CommitteeApplicationPeriodParticipation",
        ),
        migrations.DeleteModel(
            name="CommitteePriority",
        ),
    ]
