# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_auto_20151214_0117"),
        ("authentication", "0017_auto_20160128_1719"),
    ]

    operations = []
