# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0018_auto_20160224_2050"),
        ("authentication", "0018_merge"),
    ]

    operations = []
