# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("authentication", "0019_merge")]

    operations = [
        migrations.AlterField(
            model_name="onlineuser",
            name="gender",
            field=models.CharField(
                choices=[("male", "mann"), ("female", "kvinne")],
                default="male",
                max_length=10,
                verbose_name="kjønn",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="committee",
            field=models.CharField(
                choices=[
                    ("hs", "Hovedstyret"),
                    ("appkom", "Applikasjonskomiteen"),
                    ("arrkom", "Arrangementskomiteen"),
                    ("bankom", "Bank- og økonomikomiteen"),
                    ("bedkom", "Bedriftskomiteen"),
                    ("dotkom", "Drifts- og utviklingskomiteen"),
                    ("ekskom", "Ekskursjonskomiteen"),
                    ("fagkom", "Fag- og kurskomiteen"),
                    ("jubkom", "Jubileumskomiteen"),
                    ("pangkom", "Pensjonistkomiteen"),
                    ("prokom", "Profil-og aviskomiteen"),
                    ("redaksjonen", "Redaksjonen"),
                    ("trikom", "Trivselskomiteen"),
                    ("velkom", "Velkomstkomiteen"),
                ],
                default="hs",
                max_length=20,
                verbose_name="komite",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="period",
            field=models.CharField(
                default="2013-2014", max_length=9, verbose_name="periode"
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="position",
            field=models.CharField(
                choices=[
                    ("medlem", "Medlem"),
                    ("leder", "Leder"),
                    ("nestleder", "Nestleder"),
                    ("redaktor", "Redaktør"),
                    ("okoans", "Økonomiansvarlig"),
                ],
                default="medlem",
                max_length=20,
                verbose_name="stilling",
            ),
        ),
    ]
