# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineuser',
            name='field_of_study',
            field=models.SmallIntegerField(choices=[(0, 'Gjest'), (1, 'Bachelor i Informatikk'), (10, 'Programvaresystemer'), (11, 'Databaser og søk'), (12, 'Algoritmer og datamaskiner'), (13, 'Spillteknologi'), (14, 'Kunstig intelligens'), (15, 'Helseinformatikk'), (16, 'Interaksjonsdesign, spill- og læringsteknologi'), (30, 'Annen mastergrad'), (80, 'PhD'), (90, 'International'), (100, 'Annet Onlinemedlem')], default=0, verbose_name='studieretning'),
        ),
        migrations.AlterField(
            model_name='onlineuser',
            name='gender',
            field=models.CharField(choices=[('male', 'mann'), ('female', 'kvinne')], default='male', max_length=10, verbose_name='kjønn'),
        ),
        migrations.AlterField(
            model_name='position',
            name='committee',
            field=models.CharField(choices=[('hs', 'Hovedstyret'), ('appkom', 'Applikasjonskomiteen'), ('arrkom', 'Arrangementskomiteen'), ('bankom', 'Bank- og økonomikomiteen'), ('bedkom', 'Bedriftskomiteen'), ('dotkom', 'Drifts- og utviklingskomiteen'), ('ekskom', 'Ekskursjonskomiteen'), ('fagkom', 'Fag- og kurskomiteen'), ('jubkom', 'Jubileumskomiteen'), ('pangkom', 'Pensjonistkomiteen'), ('prokom', 'Profil-og aviskomiteen'), ('redaksjonen', 'Redaksjonen'), ('trikom', 'Trivselskomiteen'), ('velkom', 'Velkomstkomiteen')], default='hs', max_length=20, verbose_name='komite'),
        ),
        migrations.AlterField(
            model_name='position',
            name='period',
            field=models.CharField(default='2013-2014', max_length=9, verbose_name='periode'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(choices=[('medlem', 'Medlem'), ('leder', 'Leder'), ('nestleder', 'Nestleder'), ('redaktor', 'Redaktør'), ('okoans', 'Økonomiansvarlig')], default='medlem', max_length=20, verbose_name='stilling'),
        ),
    ]
