# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-31 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("authentication", "0020_auto_20160309_2133")]

    operations = [
        migrations.AlterField(
            model_name="registertoken",
            name="token",
            field=models.CharField(max_length=32, unique=True, verbose_name="token"),
        )
    ]
