# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("authentication", "0021_auto_20160331_0940")]

    operations = [
        migrations.AddField(
            model_name="onlineuser",
            name="internal_services_password",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Tjenester-Passord"
            ),
        )
    ]
