# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_auto_20160714_1347'),
        ('authentication', '0023_remove_onlineuser_internal_services_password'),
    ]

    operations = [
    ]
