# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-29 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("authentication", "0024_merge")]

    operations = [
        migrations.AlterField(
            model_name="onlineuser",
            name="bio",
            field=models.TextField(blank=True, max_length=2048, verbose_name="bio"),
        )
    ]
