# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 09:27
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("authentication", "0025_auto_20170529_1823")]

    operations = [
        migrations.AlterField(
            model_name="onlineuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        )
    ]
