# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 15:30
from __future__ import unicode_literals

from django.db import migrations
from django.db.migrations import RunPython


def remove_duplicate_rfids(apps, schema_editor):
    OnlineUser = apps.get_model("authentication", "OnlineUser")

    for user in OnlineUser.objects.filter(rfid=""):
        user.rfid = None
        user.save()

    for user in OnlineUser.objects.exclude(rfid__isnull=True).exclude(rfid=""):
        if OnlineUser.objects.filter(rfid=user.rfid).count() > 1:
            user.rfid = None
            user.save()


def backward(apps, schema_editor):
    # Really can't do anything to revert these changes.
    pass


class Migration(migrations.Migration):

    dependencies = [("authentication", "0026_auto_20171108_1027")]

    operations = [RunPython(remove_duplicate_rfids, backward)]
