# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_auto_20171018_2101'),
        ('authentication', '0026_auto_20171108_1027'),
    ]

    operations = [
    ]
