# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 15:35
from __future__ import unicode_literals

import apps.authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_auto_20180412_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineuser',
            name='rfid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True,
                                   validators=[apps.authentication.validators.validate_rfid], verbose_name='RFID'),
        ),
    ]
