# Generated by Django 2.0.13 on 2019-02-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_auto_20181025_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
