# Generated by Django 2.1 on 2019-04-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_auto_20181025_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedusername',
            options={'ordering': ('username',), 'permissions': (('show_allowedusername', 'Show AllowedUsername'),), 'verbose_name': 'medlem', 'verbose_name_plural': 'medlemsregister'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'permissions': (('show_email', 'Show Email'),), 'verbose_name': 'epostadresse', 'verbose_name_plural': 'epostadresser'},
        ),
        migrations.AlterModelOptions(
            name='onlineuser',
            options={'ordering': ['first_name', 'last_name'], 'permissions': (('show_onlineuser', 'Show OnlineUser'),), 'verbose_name': 'brukerprofil', 'verbose_name_plural': 'brukerprofiler'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('user', 'period'), 'permissions': (('show_position', 'Show Position'),), 'verbose_name': 'posisjon', 'verbose_name_plural': 'posisjoner'},
        ),
        migrations.AlterModelOptions(
            name='registertoken',
            options={'permissions': (('show_registertoken', 'View RegisterToken'),)},
        ),
        migrations.AlterModelOptions(
            name='specialposition',
            options={'ordering': ('user', 'since_year'), 'permissions': (('show_specialposition', 'Show SpecialPosition'),), 'verbose_name': 'spesialposisjon', 'verbose_name_plural': 'spesialposisjoner'},
        ),
        migrations.AlterField(
            model_name='onlineuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
