# Generated by Django 2.1.8 on 2019-06-02 19:40

from django.db import migrations
from django.conf import settings
from datetime import date

def load_data(apps, schema_editor):
    Position = apps.get_model('authentication', 'Position')

    for position in Position.objects.all():
        start_year, end_year = position.period.split('-')
        """ Set to start of year since that is how they were added before """
        start_date = date(int(start_year), 1, 1)
        end_date = date(int(end_year), 1, 1)
        position.period_start = start_date
        position.period_end = end_date

        position.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_auto_20190602_1939'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
