# Generated by Django 2.1.8 on 2019-06-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("authentication", "0033_convert_position_period_to_date")]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("user", "period_start", "period_end"),
                "permissions": (("view_position", "View Position"),),
                "verbose_name": "posisjon",
                "verbose_name_plural": "posisjoner",
            },
        ),
        migrations.RemoveField(model_name="position", name="period"),
        migrations.AlterField(
            model_name="position",
            name="committee",
            field=models.CharField(
                choices=[
                    ("hs", "Hovedstyret"),
                    ("appkom", "Applikasjonskomiteen"),
                    ("arrkom", "Arrangementskomiteen"),
                    ("bankom", "Bank- og økonomikomiteen"),
                    ("bedkom", "Bedriftskomiteen"),
                    ("dotkom", "Drifts- og utviklingskomiteen"),
                    ("ekskom", "Ekskursjonskomiteen"),
                    ("fagkom", "Fag- og kurskomiteen"),
                    ("jubkom", "Jubileumskomiteen"),
                    ("pangkom", "Pensjonistkomiteen"),
                    ("prokom", "Profil-og aviskomiteen"),
                    ("redaksjonen", "Redaksjonen"),
                    ("seniorkom", "Seniorkomiteen"),
                    ("trikom", "Trivselskomiteen"),
                    ("velkom", "Velkomstkomiteen"),
                ],
                default="hs",
                max_length=20,
                verbose_name="komité",
            ),
        ),
    ]
