# Generated by Django 2.1.9 on 2019-08-01 19:47

from django.db import migrations

from apps.authentication.constants import GroupType, RoleType


def load_data(apps, schema_editor):
    GroupRole = apps.get_model("authentication", "GroupRole")

    for role in GroupRole.objects.all():
        role.delete()


def revert_data(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    OnlineGroup = apps.get_model("authentication", "OnlineGroup")
    GroupMember = apps.get_model("authentication", "GroupMember")

    for group in Group.objects.all():
        online_group = OnlineGroup()
        online_group.group = group
        online_group.name_short = group.name
        online_group.name_long = group.name
        online_group.group_type = GroupType.OTHER
        online_group.save()

        for user in group.user_set.all():
            group_member = GroupMember()
            group_member.group = online_group
            group_member.user = user
            group_member.save()


class Migration(migrations.Migration):

    dependencies = [("authentication", "0037_auto_20190627_2110")]

    operations = [migrations.RunPython(load_data, revert_data)]
