# Generated by Django 2.1.9 on 2019-08-01 20:00

from django.db import migrations


from apps.authentication.constants import GroupType, RoleType


def load_data(apps, schema_editor):
    GroupRole = apps.get_model("authentication", "GroupRole")
    GroupMember = apps.get_model("authentication", "GroupMember")

    for role_type in RoleType.ALL_TYPES:
        GroupRole.objects.create(role_type=role_type)

    member_role = GroupRole.objects.get(role_type=RoleType.MEMBER)

    for group_member in GroupMember.objects.all():
        group_member.roles.add(member_role)


def revert_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [("authentication", "0039_auto_20190801_2159")]

    operations = [migrations.RunPython(load_data, revert_data)]
