# Generated by Django 2.1.11 on 2019-09-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("authentication", "0040_auto_20190801_2200")]

    operations = [
        migrations.AlterField(
            model_name="onlineuser",
            name="allergies",
            field=models.TextField(
                blank=True, null=True, verbose_name="matallergier/preferanser"
            ),
        )
    ]
