# Generated by Django 2.1.11 on 2019-09-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0041_auto_20190911_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinegroup',
            name='gsuite_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Gsuite navn'),
        ),
    ]
