# Generated by Django 2.1.11 on 2019-10-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0041_auto_20190911_2238"),
        ("marks", "0008_auto_20191009_1245"),
    ]

    operations = [migrations.RemoveField(model_name="onlineuser", name="mark_rules")]
