# Generated by Django 2.1.11 on 2019-09-17 09:05

from django.db import migrations


def load_data(apps, schema_editor):
    OnlineGroup = apps.get_model('authentication', 'OnlineGroup')

    for group in OnlineGroup.objects.all():
        if group.email:
            gsuite_name, gsuite_domain = group.email.split('@')
            group.gsuite_name = gsuite_name
            group.save()


def revert_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0042_onlinegroup_gsuite_name'),
    ]

    operations = [
        migrations.RunPython(load_data, revert_data),
    ]
