# Generated by Django 2.1.11 on 2019-09-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0042_auto_20190917_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinegroup',
            name='email',
        ),
    ]
