# Generated by Django 2.1.15 on 2020-02-19 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("authentication", "0042_remove_onlineuser_mark_rules")]

    operations = [
        migrations.AddField(
            model_name="onlinegroup",
            name="parent_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_groups",
                to="authentication.OnlineGroup",
                verbose_name="Administrerende gruppe",
            ),
        )
    ]
