# Generated by Django 2.2.10 on 2020-02-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("authentication", "0043_onlinegroup_parent_group")]

    operations = [
        migrations.AddField(
            model_name="groupmember",
            name="is_on_leave",
            field=models.BooleanField(default=False, verbose_name="Permittert"),
        ),
        migrations.AddField(
            model_name="groupmember",
            name="is_retired",
            field=models.BooleanField(default=False, verbose_name="Pensjonert"),
        ),
        migrations.AlterField(
            model_name="grouprole",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("leader", "Leder"),
                    ("deputy_leader", "Nestleder"),
                    ("treasurer", "Økonomiansvarlig"),
                    ("chief_editor", "Redaktør"),
                ],
                max_length=256,
                unique=True,
                verbose_name="Rolle",
            ),
        ),
    ]
