# Generated by Django 2.2.10 on 2020-03-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("authentication", "0045_auto_20200222_1436")]

    operations = [migrations.RemoveField(model_name="onlineuser", name="saldo")]
