# Generated by Django 3.0.4 on 2020-03-30 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0046_remove_onlineuser_saldo"),
        ("authentication", "0046_auto_20200330_0924"),
    ]

    operations = []
