# Generated by Django 3.0.6 on 2020-05-25 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0047_merge_20200330_1012"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="email",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("user", "email"),
                "permissions": (("view_email", "View Email"),),
                "verbose_name": "epostadresse",
                "verbose_name_plural": "epostadresser",
            },
        ),
    ]
