# Generated by Django 3.0.6 on 2020-07-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0047_merge_20200330_1012"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AllowedUsername",
            new_name="Membership",
        ),
        migrations.AlterModelOptions(
            name="membership",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ("username",),
                "permissions": (("view_membership", "View Membership"),),
                "verbose_name": "medlem",
                "verbose_name_plural": "medlemsregister",
            },
        ),
    ]
