# Generated by Django 3.0.9 on 2020-08-19 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0048_auto_20200720_1255"),
        ("authentication", "0048_auto_20200525_1421"),
    ]

    operations = []
