# Generated by Django 3.2.12 on 2022-03-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0050_alter_onlineuser_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onlineuser",
            name="online_mail",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Online-epost",
            ),
        ),
    ]
