# Generated by Django 3.2.23 on 2024-01-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0051_onlineuser_cognito_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlineuser",
            name="has_set_cognito_password",
            field=models.BooleanField(
                default=False, verbose_name="User has set cognito password"
            ),
        ),
    ]
