# Generated by Django 3.2.23 on 2024-02-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("authentication", "0053_onlineuser_auth0_subject"),
        ("authentication", "0054_remove_onlineuser_auth0_subject"),
        ("authentication", "0055_auto_20240201_0005"),
        ("authentication", "0056_onlineuser_auth0_subject"),
        ("authentication", "0057_alter_onlineuser_auth0_subject"),
    ]

    dependencies = [
        ("authentication", "0052_onlineuser_has_set_cognito_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="onlineuser",
            name="cognito_subject",
        ),
        migrations.RemoveField(
            model_name="onlineuser",
            name="has_set_cognito_password",
        ),
        migrations.AddField(
            model_name="onlineuser",
            name="auth0_subject",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Auth0 User Id",
            ),
        ),
    ]
