# Generated by Django 5.0.4 on 2024-04-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0055_alter_groupmember_added_alter_groupmember_group_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Email",
        ),
    ]
