# Generated by Django 5.0.4 on 2024-04-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0056_delete_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouprole",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("leader", "Leder"),
                    ("board_member", "Styremedlem"),
                    ("deputy_leader", "Nestleder"),
                    ("treasurer", "Økonomiansvarlig"),
                    ("chief_editor", "Redaktør"),
                    ("wine_penalty_manager", "Vinstraffansvarlig"),
                ],
                max_length=256,
                unique=True,
                verbose_name="Rolle",
            ),
        ),
    ]
