# Generated by Django 3.0.5 on 2020-04-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailEntity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-postadresse"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Fullt navn på organisasjonen eller e-postlisten",
                        max_length=100,
                        verbose_name="Navnet på organisasjonen",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="En kort beskrivelse av hva organisasjonen er, eller e-postlisten inneholder.",
                        null=True,
                        verbose_name="Beskrivelse",
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False,
                        help_text="Hvorvidt e-posten skal være offentlig synlig",
                        verbose_name="Offentlig synlighet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisasjon",
                "verbose_name_plural": "Organisasjoner",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MailGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_local_part",
                    models.CharField(
                        help_text="Navnet på e-postadresse, uten @online.ntnu.no",
                        max_length=50,
                        unique=True,
                        verbose_name="E-postnavn",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("online.ntnu.no", "Online Ntnu No"),
                            ("linjeforeninger.no", "Linjeforeninger No"),
                            ("itforeninger.no", "Itforeninger No"),
                            ("techtalks.no", "Techtalks No"),
                        ],
                        default="online.ntnu.no",
                        help_text="Domenet denne gruppen ligger under, f.eks. oline.ntnu.no",
                        max_length=50,
                        verbose_name="E-postdomenet",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Fullt navn på gruppen denne e-postlisten representerer, altså ikke e-postadressen",
                        max_length=100,
                        verbose_name="Navnet på gruppen",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="En forklaring på hva slags entiteter gruppen skal inneholde, og hva den kan brukes til",
                        null=True,
                        verbose_name="Beskrivelse",
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=True,
                        help_text="Hvorvidt e-postlisten skal være offentlig synlig",
                        verbose_name="Offentlig synlighet",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mailinglists",
                        to="mailinglists.MailEntity",
                        verbose_name="Organisasjoner i denne gruppen",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-postliste",
                "verbose_name_plural": "E-postlister",
                "ordering": ["domain", "email_local_part"],
            },
        ),
    ]
