# Generated by Django 2.2.10 on 2020-03-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="e-postadresse"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Fullt navn på organisasjonen eller e-postlisten",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="En kort beskrivelse av hva organisasjonen er, eller e-postlisten inneholder.",
                        null=True,
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False,
                        help_text="Hvorvidt e-posten skal være offentlig synlig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisasjons-e-post",
                "verbose_name_plural": "Organisasjons-e-poster",
            },
        ),
        migrations.CreateModel(
            name="Mailinglist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_name",
                    models.CharField(
                        help_text="Navnet på e-postadresse, uten @online.ntnu.no",
                        max_length=50,
                        unique=True,
                        verbose_name="e-postadresse",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Fullt navn på e-postlisten", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="En forklaring på hva e-postlisten skal inneholde",
                        null=True,
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=True,
                        help_text="Hvorvidt e-postlisten skal være offentlig synlig",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mailinglists_mail_is_in",
                        to="mailinglists.Mail",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-postliste",
                "verbose_name_plural": "E-postlister",
            },
        ),
    ]
