# Generated by Django 2.2.10 on 2020-03-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailinglist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="epostadresse"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("public", models.BooleanField(default=False)),
                (
                    "contained_emails",
                    models.ManyToManyField(
                        blank=True,
                        related_name="_mailinglist_contained_emails_+",
                        to="mailinglists.Mailinglist",
                    ),
                ),
            ],
        )
    ]
