# Generated by Django 3.2.23 on 2024-02-02 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mailinglists", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailgroup",
            name="members",
        ),
        migrations.DeleteModel(
            name="MailEntity",
        ),
        migrations.DeleteModel(
            name="MailGroup",
        ),
    ]
