# Generated by Django 2.1.11 on 2019-10-13 11:09

from django.db import migrations
from apps.fiken.settings import NIBBLE_ACCOUNT_IDENTIFIER


def load_data(apps, schema_editor):
    FikenAccount = apps.get_model('fiken', 'FikenAccount')

    FikenAccount.objects.get_or_create(
        identifier=NIBBLE_ACCOUNT_IDENTIFIER,
        name='Salgsinntekt Nibble',
        code='0000',
    )


def remove_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('fiken', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data, remove_data)
    ]
