# Generated by Django 2.1.11 on 2019-10-13 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("fiken", "0002_auto_20191013_1309")]

    operations = [
        migrations.AlterField(
            model_name="fikensale",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sales",
                to="fiken.FikenCustomer",
                verbose_name="Kunde",
            ),
        )
    ]
