name: Deploy / Production

on:
  release:
    types:
      - released

concurrency: deploy-prod

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      url: https://online.ntnu.no
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
