name: Deploy to develop
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_DEPLOYMENT_HOST }}
          username: ${{ secrets.DEV_DEPLOYMENT_USER }}
          key: ${{ secrets.DEV_DEPLOYMENT_KEY }}
          script: source ${{ secrets.DEV_DEPLOYMENT_SCRIPT_LOCATION }}
          timeout: 600s

