# Generated by Django 3.0.5 on 2020-05-18 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gallery", "0015_auto_20200505_1141"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("DEFAULT", "Standard varslinger"),
                            ("GROUP_MESSAGE", "Meldinger til grupper du er med i"),
                            (
                                "APPLICATIONS",
                                "Søknader (medlemskap- og komitésøknader)",
                            ),
                            ("ARTICLE_CREATED", "Nye artikler"),
                            ("REGISTRATION_OPENING", "Påmeldingsstart"),
                            ("WAIT_LIST_BUMP", "Opprykk fra venteliste"),
                            ("REGISTERED_BY_ADMIN", "Påmeldt av administrator"),
                            ("NEW_MARK", "Ny prikk"),
                            ("MARK_RULES_UPDATED", "Oppdatering av prikkereglene"),
                            ("OFFLINE_CREATED", "Nye utgaver av Offline"),
                            ("RECEIPT", "Kvitteringer"),
                        ],
                        max_length=128,
                        unique=True,
                        verbose_name="Type",
                    ),
                ),
                (
                    "force_email",
                    models.BooleanField(default=False, verbose_name="Tving e-post"),
                ),
                (
                    "force_push",
                    models.BooleanField(default=False, verbose_name="Tving pushvarsel"),
                ),
                (
                    "allow_email",
                    models.BooleanField(default=True, verbose_name="Tillat e-post"),
                ),
                (
                    "allow_push",
                    models.BooleanField(default=True, verbose_name="Tillat pushvarsel"),
                ),
                (
                    "default_value_email",
                    models.BooleanField(
                        default=False, verbose_name="Standardverdi for e-post"
                    ),
                ),
                (
                    "default_value_push",
                    models.BooleanField(
                        default=False, verbose_name="Standardverdi fro pushvarsel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Varseltillatelse",
                "verbose_name_plural": "Varseltillatelser",
                "ordering": ("permission_type",),
            },
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_email", models.BooleanField(default=False)),
                ("allow_push", models.BooleanField(default=False)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permission",
                        to="notifications.Permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_notification_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Varseltillatelse for bruker",
                "verbose_name_plural": "varseltillatelser for brukere",
                "ordering": ("permission", "user"),
                "unique_together": {("permission", "user")},
            },
        ),
        migrations.AddField(
            model_name="permission",
            name="users",
            field=models.ManyToManyField(
                related_name="notification_permissions",
                through="notifications.UserPermission",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("sent_email", models.BooleanField(default=False)),
                ("sent_push", models.BooleanField(default=False)),
                (
                    "from_mail",
                    models.EmailField(
                        default="development@online.ntnu.no", max_length=254
                    ),
                ),
                (
                    "icon",
                    models.URLField(
                        blank=True,
                        default="https://beta.online.ntnu.no/static/pwa-icon-v0-192.png",
                        max_length=1024,
                    ),
                ),
                ("title", models.CharField(max_length=60)),
                ("body", models.CharField(max_length=512)),
                ("tag", models.CharField(blank=True, max_length=50, null=True)),
                ("url", models.CharField(blank=True, default="/", max_length=1024)),
                ("require_interaction", models.BooleanField(default=False)),
                ("renotify", models.BooleanField(default=False)),
                ("silent", models.BooleanField(default=False)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="gallery.ResponsiveImage",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="notifications",
                        to="notifications.Permission",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mottaker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Varsel",
                "verbose_name_plural": "Varsler",
                "ordering": ("created_date", "recipient", "title"),
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.URLField(max_length=500, unique=True)),
                ("auth", models.CharField(max_length=500, unique=True)),
                ("p256dh", models.CharField(max_length=500, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Varselsabbonement",
                "verbose_name_plural": "Varselsabbonementer",
                "ordering": ("user", "endpoint"),
                "unique_together": {("user", "endpoint")},
            },
        ),
    ]
