# Generated by Django 2.1.8 on 2019-05-12 13:50

from django.db import migrations


def add_user_notification_settings(apps, schema_editor):
    User = apps.get_model('authentication', 'OnlineUser')
    NotificationSettings = apps.get_model('notifications', 'NotificationSettings')
    for user in User.objects.all():
        NotificationSettings.objects.create(user=user)


def undo_add_user_notification_settings(apps, schema_editor):
    NotificationSettings = apps.get_model('notifications', 'NotificationSettings')
    user_settings = NotificationSettings.objects.all()
    for settings in user_settings:
        settings.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_user_notification_settings, undo_add_user_notification_settings),
    ]
