# Generated by Django 3.0.5 on 2020-05-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_auto_20200519_1141"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="icon",
            field=models.URLField(
                blank=True,
                default="http://localhost:8000/static/img/notification-icon-192.png",
                max_length=1024,
            ),
        ),
    ]
