# Generated by Django 2.1.8 on 2019-05-12 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_auto_20190512_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('event_registration', 'event_registration'), ('event_updates', 'event_updates'), ('event_wait_list_bump', 'event_wait_list_bump'), ('feedback_created', 'feedback_created'), ('article_created', 'article_created'), ('offline_created', 'offline_created'), ('announcement', 'announcement'), ('committee_announcement', 'committee_announcement'), ('wine_punishment', 'wine_punishment')], max_length=100)),
                ('mail', models.BooleanField(default=False)),
                ('push', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
    ]
