# Generated by Django 2.1.8 on 2019-05-12 13:50

from django.db import migrations

from apps.notifications.types import NotificationType


def add_user_notification_settings(apps, schema_editor):
    User = apps.get_model('authentication', 'OnlineUser')
    NotificationSetting = apps.get_model('notifications', 'NotificationSetting')

    for user in User.objects.all():
        current_types = set([setting.message_type for setting in NotificationSetting.objects.filter(user=user)])
        missing_types = set(NotificationType.ALL_TYPES) - current_types

        for message_type in missing_types:
            NotificationSetting.objects.create(user=user, message_type=message_type)


def undo_add_user_notification_settings(apps, schema_editor):
    NotificationSetting = apps.get_model('notifications', 'NotificationSetting')
    user_settings = NotificationSetting.objects.all()
    for settings in user_settings:
        settings.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20190512_2004'),
    ]

    operations = [
        migrations.RunPython(add_user_notification_settings, undo_add_user_notification_settings),
    ]
