# Generated by Django 3.0.5 on 2020-05-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_auto_20200519_1450"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="icon",
        ),
    ]
