# Generated by Django 2.1.8 on 2019-07-13 17:39

import apps.notifications.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_auto_20190506_1719'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_create_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('event_registration', 'Arrangementspåmeldinger'), ('event_updates', 'Arrangementsoppdateringer'), ('event_wait_list_bump', 'Oppdatering av venteliste'), ('feedback_created', 'Tilbakemeldingsskjemaer'), ('article_created', 'Nye artikler'), ('offline_created', 'Nye Offline'), ('announcement', 'Oppdateringer fra Online'), ('committee_announcement', 'Oppdateringer for komiteer'), ('wine_punishment', 'Vinstraffer')], max_length=100)),
                ('sent', models.BooleanField(default=False)),
                ('icon', models.URLField(default='https://beta.online.ntnu.no/static/pwa-icon-v0-192.png')),
                ('title', models.CharField(max_length=60)),
                ('body', models.CharField(max_length=512)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('require_interaction', models.BooleanField(default=False)),
                ('renotify', models.BooleanField(default=False)),
                ('silent', models.BooleanField(default=False)),
                ('timestamp', models.IntegerField(default=apps.notifications.models.get_current_timestamp)),
                ('url', models.URLField(default='/')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='gallery.ResponsiveImage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='message_type',
            field=models.CharField(choices=[('event_registration', 'Arrangementspåmeldinger'), ('event_updates', 'Arrangementsoppdateringer'), ('event_wait_list_bump', 'Oppdatering av venteliste'), ('feedback_created', 'Tilbakemeldingsskjemaer'), ('article_created', 'Nye artikler'), ('offline_created', 'Nye Offline'), ('announcement', 'Oppdateringer fra Online'), ('committee_announcement', 'Oppdateringer for komiteer'), ('wine_punishment', 'Vinstraffer')], max_length=100),
        ),
    ]
