# Generated by Django 2.1.9 on 2019-07-13 18:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0004_auto_20190713_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'default_permissions': ('add', 'change', 'delete'), 'ordering': ('timestamp', 'user', 'title'), 'permissions': (('view_notification', 'View Notification'),), 'verbose_name': 'Varsel', 'verbose_name_plural': 'Varsler'},
        ),
        migrations.AlterModelOptions(
            name='notificationsetting',
            options={'default_permissions': ('add', 'change', 'delete'), 'ordering': ('user', 'message_type'), 'permissions': (('view_notificationsetting', 'View Notification Setting'),), 'verbose_name': 'Varselinnstilling', 'verbose_name_plural': 'Varselinnstillinger'},
        ),
        migrations.AlterModelOptions(
            name='notificationsubscription',
            options={'default_permissions': ('add', 'change', 'delete'), 'ordering': ('user', 'endpoint'), 'permissions': (('view_notificationsubscription', 'View Notification Subscription'),), 'verbose_name': 'Pushvarslingsabbonement', 'verbose_name_plural': 'Pushvarslingsabbonement'},
        ),
        migrations.AlterUniqueTogether(
            name='notificationsetting',
            unique_together={('user', 'message_type')},
        ),
        migrations.AlterUniqueTogether(
            name='notificationsubscription',
            unique_together={('user', 'endpoint')},
        ),
    ]
