# Generated by Django 3.0.6 on 2020-07-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20200721_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='from_email',
            field=models.EmailField(default='online@online.ntnu.no', max_length=254),
        ),
    ]
