# Generated by Django 3.0.6 on 2020-08-19 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0007_auto_20200814_1937"),
        ("notifications", "0007_auto_20200812_1933"),
    ]

    operations = []
