# Generated by Django 3.0.5 on 2020-04-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='service_account', max_length=80)),
                ('project_id', models.CharField(max_length=80)),
                ('private_key_id', models.CharField(max_length=80)),
                ('private_key', models.TextField()),
                ('client_email', models.EmailField(max_length=80)),
                ('client_id', models.CharField(max_length=80)),
                ('auth_uri', models.CharField(max_length=80)),
                ('token_uri', models.CharField(max_length=80)),
                ('auth_provider_x509_cert_url', models.CharField(max_length=80)),
                ('client_x509_cert_url', models.CharField(max_length=80)),
            ],
        ),
    ]
